#!/bin/bash -e

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
ROOT="$DIR/../.."
REPOSITORY_ROOT="$ROOT/.."
WORKSPACE_DIR="$ROOT/.workspace"
TMP_DIR="$WORKSPACE_DIR/tmpdir"

TECTONIC_RELEASE_BUCKET=releases.tectonic.com
TECTONIC_BINARY_BUCKET=tectonic-release
TECTONIC_RELEASE="tectonic-$VERSION"
TECTONIC_RELEASE_TARBALL_FILE="$TECTONIC_RELEASE.tar.gz"
TECTONIC_RELEASE_TARBALL_URL="https://$TECTONIC_RELEASE_BUCKET/$TECTONIC_RELEASE_TARBALL_FILE"
TECTONIC_RELEASE_DIR="$WORKSPACE_DIR/$VERSION"
TECTONIC_RELEASE_TOP_DIR="$TECTONIC_RELEASE_DIR/tectonic"
INSTALLER_RELEASE_DIR="$TECTONIC_RELEASE_TOP_DIR/tectonic-installer"

MATCHBOX_TMP_DIR="$TMP_DIR/matchbox"
MATCHBOX_RELEASE_DIR="$TECTONIC_RELEASE_TOP_DIR/matchbox"
MATCHBOX_RELEASE_VERSION=v0.5.0
MATCHBOX_RELEASE_URL="https://github.com/coreos/matchbox/releases/download/${MATCHBOX_RELEASE_VERSION}/matchbox-${MATCHBOX_RELEASE_VERSION}-linux-amd64.tar.gz"
MATCHBOX_ARCHIVE_TOP_DIR="matchbox-${MATCHBOX_RELEASE_VERSION}-linux-amd64"

TERRAFORM_BIN_TMP_DIR="$TMP_DIR/terraform-bin"
TERRAFORM_BIN_VERSION=0.9.4
TERRAFORM_BIN_BASE_URL="https://releases.hashicorp.com/terraform/${TERRAFORM_BIN_VERSION}/terraform_${TERRAFORM_BIN_VERSION}"
