package clusterapi

import (
	"context"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"time"

	"github.com/sirupsen/logrus"
	"gopkg.in/yaml.v2"
	corev1 "k8s.io/api/core/v1"
	apierrors "k8s.io/apimachinery/pkg/api/errors"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/util/wait"
	clusterv1 "sigs.k8s.io/cluster-api/api/v1beta1"
	utilkubeconfig "sigs.k8s.io/cluster-api/util/kubeconfig"
	"sigs.k8s.io/controller-runtime/pkg/client"

	"github.com/openshift/installer/pkg/asset"
	"github.com/openshift/installer/pkg/asset/cluster/metadata"
	"github.com/openshift/installer/pkg/asset/cluster/tfvars"
	"github.com/openshift/installer/pkg/asset/ignition/bootstrap"
	"github.com/openshift/installer/pkg/asset/ignition/machine"
	"github.com/openshift/installer/pkg/asset/installconfig"
	"github.com/openshift/installer/pkg/asset/kubeconfig"
	"github.com/openshift/installer/pkg/asset/machines"
	"github.com/openshift/installer/pkg/asset/manifests"
	"github.com/openshift/installer/pkg/asset/manifests/capiutils"
	capimanifests "github.com/openshift/installer/pkg/asset/manifests/clusterapi"
	"github.com/openshift/installer/pkg/asset/rhcos"
	"github.com/openshift/installer/pkg/clusterapi"
	"github.com/openshift/installer/pkg/infrastructure"
	"github.com/openshift/installer/pkg/metrics/timer"
	"github.com/openshift/installer/pkg/types"
)

// Ensure that clusterapi.InfraProvider implements
// the infrastructure.Provider interface, which is the
// interface the installer uses to call this provider.
var _ infrastructure.Provider = (*InfraProvider)(nil)

const (
	// timeout for each provisioning step.
	timeout = 15 * time.Minute

	preProvisionStage        = "Infrastructure Pre-provisioning"
	infrastructureStage      = "Network-infrastructure Provisioning"
	infrastructureReadyStage = "Post-network, pre-machine Provisioning"
	ignitionStage            = "Bootstrap Ignition Provisioning"
	machineStage             = "Machine Provisioning"
	postProvisionStage       = "Infrastructure Post-provisioning"

	// CAPIArtifactsDir is the directory where the manifests generated by CAPI are stored.
	CAPIArtifactsDir = ".clusterapi_output"
)

// InfraProvider implements common Cluster API logic and
// contains the platform CAPI provider, which is called
// in the lifecycle defined by the Provider interface.
type InfraProvider struct {
	impl Provider
}

// InitializeProvider returns a ClusterAPI provider implementation
// for a specific cloud platform.
func InitializeProvider(platform Provider) infrastructure.Provider {
	return &InfraProvider{impl: platform}
}

// Provision creates cluster resources by applying CAPI manifests to a locally running control plane.
//
//nolint:gocyclo
func (i *InfraProvider) Provision(ctx context.Context, dir string, parents asset.Parents) ([]*asset.File, error) {
	manifestsAsset := &manifests.Manifests{}
	workersAsset := &machines.Worker{}
	capiManifestsAsset := &capimanifests.Cluster{}
	capiMachinesAsset := &machines.ClusterAPI{}
	clusterKubeconfigAsset := &kubeconfig.AdminClient{}
	clusterID := &installconfig.ClusterID{}
	installConfig := &installconfig.InstallConfig{}
	rhcosImage := new(rhcos.Image)
	bootstrapIgnAsset := &bootstrap.Bootstrap{}
	masterIgnAsset := &machine.Master{}
	tfvarsAsset := &tfvars.TerraformVariables{}
	parents.Get(
		manifestsAsset,
		workersAsset,
		capiManifestsAsset,
		clusterKubeconfigAsset,
		clusterID,
		installConfig,
		rhcosImage,
		bootstrapIgnAsset,
		masterIgnAsset,
		capiMachinesAsset,
		tfvarsAsset,
	)

	fileList := []*asset.File{}

	// Collect cluster and non-machine-related infra manifests
	// to be applied during the initial stage.
	infraManifests := []client.Object{}
	for _, m := range capiManifestsAsset.RuntimeFiles() {
		infraManifests = append(infraManifests, m.Object)
	}

	// Machine manifests will be applied after the infra
	// manifests and subsequent hooks.
	machineManifests := []client.Object{}
	for _, m := range capiMachinesAsset.RuntimeFiles() {
		machineManifests = append(machineManifests, m.Object)
	}

	if p, ok := i.impl.(PreProvider); ok {
		preProvisionInput := PreProvisionInput{
			InfraID:          clusterID.InfraID,
			InstallConfig:    installConfig,
			RhcosImage:       rhcosImage,
			ManifestsAsset:   manifestsAsset,
			MachineManifests: machineManifests,
			WorkersAsset:     workersAsset,
		}
		timer.StartTimer(preProvisionStage)
		if err := p.PreProvision(ctx, preProvisionInput); err != nil {
			return fileList, fmt.Errorf("failed during pre-provisioning: %w", err)
		}
		timer.StopTimer(preProvisionStage)
	} else {
		logrus.Debugf("No pre-provisioning requirements for the %s provider", i.impl.Name())
	}

	// Run the CAPI system.
	timer.StartTimer(infrastructureStage)
	capiSystem := clusterapi.System()
	if err := capiSystem.Run(ctx); err != nil {
		return fileList, fmt.Errorf("failed to run cluster api system: %w", err)
	}

	// Grab the client.
	cl := capiSystem.Client()

	// Create the infra manifests.
	for _, m := range infraManifests {
		m.SetNamespace(capiutils.Namespace)
		if err := cl.Create(ctx, m); err != nil {
			return fileList, fmt.Errorf("failed to create infrastructure manifest: %w", err)
		}
		logrus.Infof("Created manifest %+T, namespace=%s name=%s", m, m.GetNamespace(), m.GetName())
	}

	// Pass cluster kubeconfig and store it in; this is usually the role of a bootstrap provider.
	{
		key := client.ObjectKey{
			Name:      clusterID.InfraID,
			Namespace: capiutils.Namespace,
		}
		cluster := &clusterv1.Cluster{}
		if err := cl.Get(ctx, key, cluster); err != nil {
			return fileList, err
		}
		// Create the secret.
		clusterKubeconfig := clusterKubeconfigAsset.Files()[0].Data
		secret := utilkubeconfig.GenerateSecret(cluster, clusterKubeconfig)
		if err := cl.Create(ctx, secret); err != nil {
			return fileList, err
		}
	}

	// Wait for successful provisioning by checking the InfrastructureReady
	// status on the cluster object.
	untilTime := time.Now().Add(timeout)
	timezone, _ := untilTime.Zone()
	logrus.Infof("Waiting up to %v (until %v %s) for network infrastructure to become ready...", timeout, untilTime.Format(time.Kitchen), timezone)
	var cluster *clusterv1.Cluster
	{
		if err := wait.ExponentialBackoffWithContext(ctx, wait.Backoff{
			Duration: time.Second * 10,
			Factor:   float64(1.5),
			Steps:    32,
			Cap:      timeout,
		}, func(ctx context.Context) (bool, error) {
			c := &clusterv1.Cluster{}
			if err := cl.Get(ctx, client.ObjectKey{
				Name:      clusterID.InfraID,
				Namespace: capiutils.Namespace,
			}, c); err != nil {
				if apierrors.IsNotFound(err) {
					return false, nil
				}
				return false, err
			}
			cluster = c
			return cluster.Status.InfrastructureReady, nil
		}); err != nil {
			if wait.Interrupted(err) {
				return fileList, fmt.Errorf("infrastructure was not ready within %v: %w", timeout, err)
			}
			return fileList, fmt.Errorf("infrastructure is not ready: %w", err)
		}
		if cluster == nil {
			return fileList, fmt.Errorf("error occurred during load balancer ready check")
		}
		if cluster.Spec.ControlPlaneEndpoint.Host == "" {
			return fileList, fmt.Errorf("control plane endpoint is not set")
		}
	}
	timer.StopTimer(infrastructureStage)
	logrus.Info("Network infrastructure is ready")

	if p, ok := i.impl.(InfraReadyProvider); ok {
		infraReadyInput := InfraReadyInput{
			Client:        cl,
			InstallConfig: installConfig,
			InfraID:       clusterID.InfraID,
		}

		timer.StartTimer(infrastructureReadyStage)
		if err := p.InfraReady(ctx, infraReadyInput); err != nil {
			return fileList, fmt.Errorf("failed provisioning resources after infrastructure ready: %w", err)
		}
		timer.StopTimer(infrastructureReadyStage)
	} else {
		logrus.Debugf("No infrastructure ready requirements for the %s provider", i.impl.Name())
	}

	bootstrapIgnData, err := injectInstallInfo(bootstrapIgnAsset.Files()[0].Data)
	if err != nil {
		return nil, fmt.Errorf("unable to inject installation info: %w", err)
	}

	// The cloud-platform may need to override the default
	// bootstrap ignition behavior.
	if p, ok := i.impl.(IgnitionProvider); ok {
		ignInput := IgnitionInput{
			Client:           cl,
			BootstrapIgnData: bootstrapIgnData,
			InfraID:          clusterID.InfraID,
			InstallConfig:    installConfig,
			TFVarsAsset:      tfvarsAsset,
		}

		timer.StartTimer(ignitionStage)
		if bootstrapIgnData, err = p.Ignition(ctx, ignInput); err != nil {
			return fileList, fmt.Errorf("failed preparing ignition data: %w", err)
		}
		timer.StopTimer(ignitionStage)
	} else {
		logrus.Debugf("No Ignition requirements for the %s provider", i.impl.Name())
	}
	bootstrapIgnSecret := IgnitionSecret(bootstrapIgnData, clusterID.InfraID, "bootstrap")
	masterIgnSecret := IgnitionSecret(masterIgnAsset.Files()[0].Data, clusterID.InfraID, "master")
	machineManifests = append(machineManifests, bootstrapIgnSecret, masterIgnSecret)

	timer.StartTimer(machineStage)
	// Create the machine manifests.
	for _, m := range machineManifests {
		m.SetNamespace(capiutils.Namespace)
		if err := cl.Create(ctx, m); err != nil {
			return fileList, fmt.Errorf("failed to create control-plane manifest: %w", err)
		}
		logrus.Infof("Created manifest %+T, namespace=%s name=%s", m, m.GetNamespace(), m.GetName())
	}

	{
		masterCount := int64(1)
		if reps := installConfig.Config.ControlPlane.Replicas; reps != nil {
			masterCount = *reps
		}

		untilTime := time.Now().Add(timeout)
		timezone, _ := untilTime.Zone()
		logrus.Infof("Waiting up to %v (until %v %s) for machines to provision...", timeout, untilTime.Format(time.Kitchen), timezone)
		if err := wait.ExponentialBackoffWithContext(ctx, wait.Backoff{
			Duration: time.Second * 10,
			Factor:   float64(1.5),
			Steps:    32,
			Cap:      timeout,
		}, func(ctx context.Context) (bool, error) {
			for i := int64(0); i < masterCount; i++ {
				machine := &clusterv1.Machine{}
				if err := cl.Get(ctx, client.ObjectKey{
					Name:      fmt.Sprintf("%s-%s-%d", clusterID.InfraID, "master", i),
					Namespace: capiutils.Namespace,
				}, machine); err != nil {
					if apierrors.IsNotFound(err) {
						logrus.Debugf("Not found")
						return false, nil
					}
					return false, err
				}
				if machine.Status.Phase != string(clusterv1.MachinePhaseProvisioned) &&
					machine.Status.Phase != string(clusterv1.MachinePhaseRunning) {
					return false, nil
				} else if machine.Status.Phase == string(clusterv1.MachinePhaseFailed) {
					return false, fmt.Errorf("machine %s failed to provision: %q", machine.Name, *machine.Status.FailureMessage)
				}
				logrus.Debugf("Machine %s is ready. Phase: %s", machine.Name, machine.Status.Phase)
			}
			return true, nil
		}); err != nil {
			if wait.Interrupted(err) {
				return fileList, fmt.Errorf("control-plane machines were not provisioned within %v: %w", timeout, err)
			}
			return fileList, fmt.Errorf("control-plane machines are not ready: %w", err)
		}
	}
	timer.StopTimer(machineStage)
	logrus.Info("Control-plane machines are ready")

	if p, ok := i.impl.(PostProvider); ok {
		postMachineInput := PostProvisionInput{
			Client:        cl,
			InstallConfig: installConfig,
			InfraID:       clusterID.InfraID,
		}

		timer.StartTimer(postProvisionStage)
		if err = p.PostProvision(ctx, postMachineInput); err != nil {
			return fileList, fmt.Errorf("failed during post-machine creation hook: %w", err)
		}
		timer.StopTimer(postProvisionStage)
	}

	// For each manifest we created, retrieve it and store it in the asset.
	manifests := []client.Object{}
	manifests = append(manifests, infraManifests...)
	manifests = append(manifests, machineManifests...)
	for _, m := range manifests {
		key := client.ObjectKey{
			Name:      m.GetName(),
			Namespace: m.GetNamespace(),
		}
		if err := cl.Get(ctx, key, m); err != nil {
			return fileList, fmt.Errorf("failed to get manifest: %w", err)
		}

		gvk, err := cl.GroupVersionKindFor(m)
		if err != nil {
			return fileList, fmt.Errorf("failed to get GVK for manifest: %w", err)
		}
		fileName := filepath.Join(CAPIArtifactsDir, fmt.Sprintf("%s-%s-%s.yaml", gvk.Kind, m.GetNamespace(), m.GetName()))
		objData, err := yaml.Marshal(m)
		if err != nil {
			return fileList, fmt.Errorf("failed to create infrastructure manifest %s from InstallConfig: %w", fileName, err)
		}
		fileList = append(fileList, &asset.File{
			Filename: fileName,
			Data:     objData,
		})
	}

	logrus.Infof("Cluster API resources have been created. Waiting for cluster to become ready...")

	// If we're skipping bootstrap destroy, shutdown the local control plane.
	// Otherwise, we will shut it down after bootstrap destroy.
	if oi, ok := os.LookupEnv("OPENSHIFT_INSTALL_PRESERVE_BOOTSTRAP"); ok && oi != "" {
		logrus.Warn("OPENSHIFT_INSTALL_PRESERVE_BOOTSTRAP is set, shutting down local control plane.")
		clusterapi.System().Teardown()
	}

	return fileList, nil
}

// DestroyBootstrap destroys the temporary bootstrap resources.
func (i *InfraProvider) DestroyBootstrap(ctx context.Context, dir string) error {
	metadata, err := metadata.Load(dir)
	if err != nil {
		return err
	}

	sys := clusterapi.System()
	if sys.State() != clusterapi.SystemStateRunning {
		if err := sys.Run(ctx); err != nil {
			return fmt.Errorf("failed to run capi system: %w", err)
		}
	}

	machineName := capiutils.GenerateBoostrapMachineName(metadata.InfraID)
	machineNamespace := capiutils.Namespace
	if err := sys.Client().Delete(ctx, &clusterv1.Machine{
		ObjectMeta: metav1.ObjectMeta{
			Name:      machineName,
			Namespace: machineNamespace,
		},
	}); err != nil {
		return fmt.Errorf("failed to delete bootstrap machine: %w", err)
	}

	machineDeletionTimeout := 5 * time.Minute
	logrus.Infof("Waiting up to %v for bootstrap machine deletion %s/%s...", machineDeletionTimeout, machineNamespace, machineName)
	ctx, cancel := context.WithTimeout(ctx, machineDeletionTimeout)
	wait.UntilWithContext(ctx, func(context.Context) {
		err := sys.Client().Get(ctx, client.ObjectKey{
			Name:      machineName,
			Namespace: machineNamespace,
		}, &clusterv1.Machine{})
		if err != nil {
			if apierrors.IsNotFound(err) {
				logrus.Debugf("Machine deleted: %s", machineName)
				cancel()
			} else {
				logrus.Debugf("Error when deleting bootstrap machine: %s", err)
			}
		}
	}, 2*time.Second)

	err = ctx.Err()
	if err != nil && !errors.Is(err, context.Canceled) {
		logrus.Warnf("Timeout deleting bootstrap machine: %s", err)
	} else {
		logrus.Infof("Finished destroying bootstrap resources")
	}
	clusterapi.System().Teardown()

	return nil
}

type machineManifest struct {
	Status struct {
		Addresses []clusterv1.MachineAddress `yaml:"addresses"`
	} `yaml:"status"`
}

// extractIPAddress extracts the IP address from a machine manifest file in a
// provider-agnostic way by reading only the "status" stanza, which should be
// present in all providers.
func extractIPAddress(manifestPath string) (string, error) {
	data, err := os.ReadFile(manifestPath)
	if err != nil {
		return "", fmt.Errorf("failed to read machine manifest %s: %w", manifestPath, err)
	}
	var manifest machineManifest
	if err := yaml.Unmarshal(data, &manifest); err != nil {
		return "", fmt.Errorf("failed to unmarshal manifest %s: %w", manifestPath, err)
	}

	var ipAddr string
	for _, addr := range manifest.Status.Addresses {
		switch addr.Type {
		case clusterv1.MachineExternalIP:
			ipAddr = addr.Address
		case clusterv1.MachineInternalIP:
			// Prefer external IP when present
			if len(ipAddr) == 0 {
				ipAddr = addr.Address
			}
		default:
			continue
		}
	}

	return ipAddr, nil
}

// ExtractHostAddresses extracts the IPs of the bootstrap and control plane machines.
func (i *InfraProvider) ExtractHostAddresses(dir string, config *types.InstallConfig, ha *infrastructure.HostAddresses) error {
	manifestsDir := filepath.Join(dir, CAPIArtifactsDir)
	logrus.Debugf("Looking for machine manifests in %s", manifestsDir)

	bootstrapFiles, err := filepath.Glob(filepath.Join(manifestsDir, "Machine\\-openshift\\-cluster\\-api\\-guests\\-*\\-bootstrap.yaml"))
	if err != nil {
		return fmt.Errorf("failed to list bootstrap manifests: %w", err)
	}
	logrus.Debugf("bootstrap manifests found: %v", bootstrapFiles)

	if len(bootstrapFiles) != 1 {
		return fmt.Errorf("wrong number of bootstrap manifests found: %v. Expected exactly one", bootstrapFiles)
	}
	addr, err := extractIPAddress(bootstrapFiles[0])
	if err != nil {
		return fmt.Errorf("failed to extract IP address for bootstrap: %w", err)
	}
	logrus.Debugf("found bootstrap address: %s", addr)
	ha.Bootstrap = addr

	masterFiles, err := filepath.Glob(filepath.Join(manifestsDir, "Machine\\-openshift\\-cluster\\-api\\-guests\\-*\\-master\\-?.yaml"))
	if err != nil {
		return fmt.Errorf("failed to list master machine manifests: %w", err)
	}
	logrus.Debugf("master machine manifests found: %v", masterFiles)

	if replicas := int(*config.ControlPlane.Replicas); replicas != len(masterFiles) {
		logrus.Warnf("not all master manifests found: %d. Expected %d.", len(masterFiles), replicas)
	}
	for _, manifest := range masterFiles {
		addr, err := extractIPAddress(manifest)
		if err != nil {
			// Log the error but keep parsing the remaining files
			logrus.Warnf("failed to extract IP address for %s: %v", manifest, err)
			continue
		}
		logrus.Debugf("found master address: %s", addr)
		ha.Masters = append(ha.Masters, addr)
	}

	return nil
}

// IgnitionSecret provides the basic formatting for creating the
// ignition secret.
func IgnitionSecret(ign []byte, infraID, role string) *corev1.Secret {
	secret := &corev1.Secret{
		ObjectMeta: metav1.ObjectMeta{
			Name:      fmt.Sprintf("%s-%s", infraID, role),
			Namespace: capiutils.Namespace,
			Labels: map[string]string{
				"cluster.x-k8s.io/cluster-name": infraID,
			},
		},
		Data: map[string][]byte{
			"format": []byte("ignition"),
			"value":  ign,
		},
	}
	secret.SetGroupVersionKind(corev1.SchemeGroupVersion.WithKind("Secret"))
	return secret
}
