#!/bin/bash

set -euo pipefail

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

pushd "$SCRIPT_DIR" > /dev/null

LD_FLAGS="-w -X github.com/coreos-inc/tectonic/stats-extender/pkg/version.Version=$(../git-version)"

GOOS=linux CGO_ENABLED=0 go build -o bin/extender -ldflags="$LD_FLAGS" -a -tags netgo github.com/coreos-inc/tectonic/stats-extender/cmd/extender

popd > /dev/null
