# Required Python packages:
#
# ansible
# openstacksdk
# netaddr

- hosts: all

  vars:
    cluster_subnet: "{{ os_infra_id }}-nodes"

  tasks:
  - name: 'Create the cluster network'
    os_network:
      name: "{{ os_network }}"

  - name: 'Create a subnet'
    os_subnet:
      name: "{{ cluster_subnet }}"
      network_name: "{{ os_network }}"
      cidr: "{{ os_subnet_range }}"
      allocation_pool_start: "{{ os_subnet_range | next_nth_usable(10) }}"
      allocation_pool_end: "{{ os_subnet_range | ipaddr('last_usable') }}"
