# Required Python packages:
#
# ansible
# openstacksdk
# netaddr

- hosts: all
  gather_facts: no

  vars_files:
  - metadata.json
  vars:
    nodes_subnet: "{{ infraID }}-nodes"
    os_network: "{{ infraID }}-network"
    os_router: "{{ infraID }}-router"

  tasks:
  - name: 'Create the cluster network'
    os_network:
      name: "{{ os_network }}"

  - name: 'Create a subnet'
    os_subnet:
      name: "{{ nodes_subnet }}"
      network_name: "{{ os_network }}"
      cidr: "{{ os_subnet_range }}"
      allocation_pool_start: "{{ os_subnet_range | next_nth_usable(10) }}"
      allocation_pool_end: "{{ os_subnet_range | ipaddr('last_usable') }}"

  - name: 'Create external router'
    os_router:
      name: "{{ os_router }}"
      network: "{{ os_external_network }}"
      interfaces:
      - "{{ nodes_subnet }}"
