- import_playbook: common.yaml

- hosts: all
  gather_facts: no

  tasks:
  - name: 'Set MTU for the first neutron network'
    command:
      cmd: "openstack networrk set {{ os_network }} --mtu {{ neutron_network_mtu }}"
    when: os_networking_type == "CiscoACI"

  - name: 'Create ACI containers node network'
    command:
      cmd: "neutron net-create {{ os_aci_containers_network }} --apic:nested-domain-name openshift-domain --apic:nested-domain-type openshift --apic:nested_domain_infra_vlan {{ infra_vlan }} --apic:nested_domain_service_vlan {{ service_vlan }}"
    when: os_networking_type == "CiscoACI"

  - name: 'Set the ACI containers cluster network tag'
    command:
      cmd: "openstack network set --tag {{ cluster_id_tag }} {{ os_aci_containers_network }}"
    when: os_networking_type == "CiscoACI"

  - name: 'Create the ACI containers subnet'
    os_subnet:
      name: "{{ os_aci_containers_subnet }}"
      network_name: "{{ os_aci_containers_network }}"
      no_gateway_ip: yes
      cidr: "{{ os_aci_containers_subnet_range }}"
      allocation_pool_start: "{{ os_aci_containers_subnet_range | next_nth_usable(10) }}"
      allocation_pool_end: "{{ os_aci_containers_subnet_range | ipaddr('last_usable') }}"
    when: os_networking_type == "CiscoACI"

  - name: 'Set the ACI containers cluster subnet tag'
    command:
      cmd: "openstack subnet set --tag {{ cluster_id_tag }} {{ os_aci_containers_subnet }}"
    when: os_networking_type == "CiscoACI"

  - name: 'Set dns nameserver'
    command:
      cmd: "openstack subnet set --dns-nameserver {{ dns_ip }} {{ os_subnet }}"
    when: os_networking_type == "CiscoACI"
