# Required Python packages:
#
# ansible
# openstacksdk

- hosts: all
  gather_facts: no

  tasks:
  - name: 'Remove the master security group'
    os_security_group:
      name: "{{ os_sg_master }}"
      state: absent

  - name: 'Remove the worker security group'
    os_security_group:
      name: "{{ os_sg_worker }}"
      state: absent
