# Required Python packages:
#
# ansible
# openstacksdk

- hosts: all

  vars_files:
  - metadata.json
  vars:
    os_network: "{{ infraID }}-network"
    os_router: "{{ infraID }}-router"


  tasks:
  - name: 'Remove the cluster router'
    os_router:
      name: "{{ os_router }}"
      state: absent
  - name: 'Remove the cluster network'
    os_network:
      name: "{{ os_network }}"
      state: absent
