# Required Python packages:
#
# ansible
# openstackclient
# openstacksdk

- import_playbook: common.yaml

- hosts: all
  gather_facts: false

  tasks:
  - name: 'Remove the Control Plane servers'
    os_server:
      name: "{{ item }}-{{ index_server }}"
      state: absent
    loop: "{{ [os_cp_server_name] * os_cp_nodes_number }}"
    loop_control:
      index_var: index_server

  - name: 'List the Server groups'
    command:
      # os-compute-api-version 2.15 or higher is required for the 'soft-anti-affinity' policy
      cmd: "openstack --os-compute-api-version=2.15 server group list -f json -c ID -c Name"
    register: server_group_list

  - name: 'Parse the Server group ID from existing'
    set_fact:
      server_group_id: "{{ (server_group_list.stdout | from_json | json_query(list_query) | first).ID }}"
    vars:
      list_query: "[?Name=='{{ os_cp_server_group_name }}']"
    when:
    - "os_cp_server_group_name|string in server_group_list.stdout"

  - name: 'Remove the Control Plane server group'
    command:
      # os-compute-api-version 2.15 or higher is required for the 'soft-anti-affinity' policy
      cmd: "openstack --os-compute-api-version=2.15 server group delete {{ server_group_id }}"
    when:
    - server_group_id is defined

  - name: 'List the Compute trunks'
    command:
      cmd: "openstack network trunk list -c Name -f value"
    when: os_networking_type == "Kuryr"
    register: trunks

  - name: 'Remove the Control Plane trunks'
    command:
      cmd: "openstack network trunk delete {{ item }}-{{ index_trunk }}"
    when:
    - os_networking_type == "Kuryr"
    - (item|string + '-' + index_trunk|string) in trunks.stdout_lines|list
    loop: "{{ [os_cp_trunk_name] * os_cp_nodes_number }}"
    loop_control:
      index_var: index_trunk

  - name: 'Remove the Control Plane ports'
    os_port:
      name: "{{ item }}-{{ index_port }}"
      state: absent
    loop: "{{ [os_port_master] * os_cp_nodes_number }}"
    loop_control:
      index_var: index_port
