# Required Python packages:
#
# ansible
# openstacksdk

- hosts: all
  gather_facts: no

  vars_files:
  - metadata.json
  vars:
    os_sg_master: "{{ infraID }}-master"
    os_sg_worker: "{{ infraID }}-worker"

  tasks:
  - name: 'Remove the master security group'
    os_security_group:
      name: "{{ os_sg_master }}"
      state: absent

  - name: 'Remove the worker security group'
    os_security_group:
      name: "{{ os_sg_worker }}"
      state: absent
