#!/usr/bin/env bash

set -e

# pull the current git commit hash
VERSION=$(git rev-parse HEAD)

# check if the current commit has a matching tag,
# and prepend the matching tag to the version, if available.
TAG=$(git describe --exact-match --abbrev=0 --tags ${VERSION} 2> /dev/null || true)
if [ ! -z "$TAG" ]; then
	VERSION=${TAG}_${VERSION}
fi

# check for changed files (not untracked files)
if [ -n "$(git diff --shortstat 2> /dev/null | tail -n1)" ]; then
	VERSION="${VERSION}_dirty"
fi

echo "$VERSION"
