# This variable set the release version.
# 
# BEFORE building an official release, please update it 
# with the actual release version string.
#
# THIS FILE SHOULD BE AUTOGENERATED BY RELEASE AUTOMATION.

TECTONIC_VERSION="dev"
