package bootkube

import (
	"os"
	"path/filepath"

	"github.com/openshift/installer/pkg/asset"
	"github.com/openshift/installer/pkg/asset/templates/content"
)

const (
	tectonicNamespaceFileName = "01-tectonic-namespace.yaml"
)

var _ asset.WritableAsset = (*TectonicNamespace)(nil)

// TectonicNamespace is the constant to represent contents of Tectonic_Namespace.yaml file
type TectonicNamespace struct {
	fileName string
	FileList []*asset.File
}

// Dependencies returns all of the dependencies directly needed by the asset
func (t *TectonicNamespace) Dependencies() []asset.Asset {
	return []asset.Asset{}
}

// Name returns the human-friendly name of the asset.
func (t *TectonicNamespace) Name() string {
	return "TectonicNamespace"
}

// Generate generates the actual files by this asset
func (t *TectonicNamespace) Generate(parents asset.Parents) error {
	t.fileName = tectonicNamespaceFileName
	data, err := content.GetBootkubeTemplate(t.fileName)
	if err != nil {
		return err
	}
	t.FileList = []*asset.File{
		{
			Filename: filepath.Join(content.TemplateDir, t.fileName),
			Data:     []byte(data),
		},
	}
	return nil
}

// Files returns the files generated by the asset.
func (t *TectonicNamespace) Files() []*asset.File {
	// Files returns the files generated by the asset.
	return t.FileList
}

// Load returns the asset from disk.
func (t *TectonicNamespace) Load(f asset.FileFetcher) (bool, error) {
	file, err := f.FetchByName(filepath.Join(content.TemplateDir, tectonicNamespaceFileName))
	if err != nil {
		if os.IsNotExist(err) {
			return false, nil
		}
		return false, err
	}
	t.FileList = []*asset.File{file}
	return true, nil
}
