package bootkube

import (
	"os"
	"path/filepath"

	"github.com/openshift/installer/pkg/asset"
	"github.com/openshift/installer/pkg/asset/templates/content"
)

const (
	openshiftServiceCAOperatorNamespaceFileName = "09-openshift-service-ca-operator-namespace.yaml"
)

var _ asset.WritableAsset = (*OpenshiftServiceCAOperatorNamespace)(nil)

// OpenshiftServiceCAOperatorNamespace is the constant to represent the contents of 09-openshift-service-ca-operator-namespace.yaml
type OpenshiftServiceCAOperatorNamespace struct {
	FileList []*asset.File
}

// Dependencies returns all of the dependencies directly needed by the asset
func (t *OpenshiftServiceCAOperatorNamespace) Dependencies() []asset.Asset {
	return []asset.Asset{}
}

// Name returns the human-friendly name of the asset.
func (t *OpenshiftServiceCAOperatorNamespace) Name() string {
	return "OpenshiftServiceCAOperatorNamespace"
}

// Generate generates the actual files by this asset
func (t *OpenshiftServiceCAOperatorNamespace) Generate(parents asset.Parents) error {
	fileName := openshiftServiceCAOperatorNamespaceFileName
	data, err := content.GetBootkubeTemplate(fileName)
	if err != nil {
		return err
	}
	t.FileList = []*asset.File{
		{
			Filename: filepath.Join(content.TemplateDir, fileName),
			Data:     []byte(data),
		},
	}
	return nil
}

// Files returns the files generated by the asset.
func (t *OpenshiftServiceCAOperatorNamespace) Files() []*asset.File {
	return t.FileList
}

// Load returns the asset from disk.
func (t *OpenshiftServiceCAOperatorNamespace) Load(f asset.FileFetcher) (bool, error) {
	file, err := f.FetchByName(filepath.Join(content.TemplateDir, openshiftServiceCAOperatorNamespaceFileName))
	if err != nil {
		if os.IsNotExist(err) {
			return false, nil
		}
		return false, err
	}
	t.FileList = []*asset.File{file}
	return true, nil
}
