package bootkube

import (
	"os"
	"path/filepath"

	"github.com/openshift/installer/pkg/asset"
	"github.com/openshift/installer/pkg/asset/templates/content"
)

const (
	appVersionTectonicNetworkFileName = "app-version-tectonic-network.yaml"
)

var _ asset.WritableAsset = (*AppVersionTectonicNetwork)(nil)

// AppVersionTectonicNetwork is the constant to represent contents of App_VersionTectonicNetwork.yaml file
type AppVersionTectonicNetwork struct {
	fileName string
	FileList []*asset.File
}

// Dependencies returns all of the dependencies directly needed by the asset
func (t *AppVersionTectonicNetwork) Dependencies() []asset.Asset {
	return []asset.Asset{}
}

// Name returns the human-friendly name of the asset.
func (t *AppVersionTectonicNetwork) Name() string {
	return "AppVersionTectonicNetwork"
}

// Generate generates the actual files by this asset
func (t *AppVersionTectonicNetwork) Generate(parents asset.Parents) error {
	t.fileName = appVersionTectonicNetworkFileName
	data, err := content.GetBootkubeTemplate(t.fileName)
	if err != nil {
		return err
	}
	t.FileList = []*asset.File{
		{
			Filename: filepath.Join(content.TemplateDir, t.fileName),
			Data:     []byte(data),
		},
	}
	return nil
}

// Files returns the files generated by the asset.
func (t *AppVersionTectonicNetwork) Files() []*asset.File {
	return t.FileList
}

// Load returns the asset from disk.
func (t *AppVersionTectonicNetwork) Load(f asset.FileFetcher) (bool, error) {
	file, err := f.FetchByName(filepath.Join(content.TemplateDir, appVersionTectonicNetworkFileName))
	if err != nil {
		if os.IsNotExist(err) {
			return false, nil
		}
		return false, err
	}
	t.FileList = []*asset.File{file}
	return true, nil
}
