package bootkube

import (
	"os"
	"path/filepath"

	"github.com/sirupsen/logrus"

	"github.com/openshift/installer/pkg/asset"
	"github.com/openshift/installer/pkg/asset/templates/content"
)

const (
	etcdServiceFileName = "etcd-service.yaml"
)

var _ asset.WritableAsset = (*EtcdService)(nil)

// EtcdService is an asset for the etcd service
type EtcdService struct {
	FileList []*asset.File
}

// Dependencies returns all of the dependencies directly needed by the asset
func (t *EtcdService) Dependencies() []asset.Asset {
	return []asset.Asset{}
}

// Name returns the human-friendly name of the asset.
func (t *EtcdService) Name() string {
	return "EtcdService"
}

// Generate generates the actual files by this asset
func (t *EtcdService) Generate(log *logrus.Entry, parents asset.Parents) error {
	fileName := etcdServiceFileName
	data, err := content.GetBootkubeTemplate(fileName)
	if err != nil {
		return err
	}
	t.FileList = []*asset.File{
		{
			Filename: filepath.Join(content.TemplateDir, fileName),
			Data:     []byte(data),
		},
	}
	return nil
}

// Files returns the files generated by the asset.
func (t *EtcdService) Files() []*asset.File {
	return t.FileList
}

// Load returns the asset from disk.
func (t *EtcdService) Load(f asset.FileFetcher) (bool, error) {
	file, err := f.FetchByName(filepath.Join(content.TemplateDir, etcdServiceFileName))
	if err != nil {
		if os.IsNotExist(err) {
			return false, nil
		}
		return false, err
	}
	t.FileList = []*asset.File{file}
	return true, nil
}
