package bootkube

import (
	"context"
	"os"
	"path/filepath"

	"github.com/openshift/api/features"
	"github.com/openshift/installer/pkg/asset"
	"github.com/openshift/installer/pkg/asset/installconfig"
	"github.com/openshift/installer/pkg/asset/templates/content"
	"github.com/openshift/installer/pkg/asset/templates/content/manifests"
)

const (
	internalReleaseImageTLSSecretFileName = "internal-release-image-tls-secret.yaml.template"
)

var _ asset.WritableAsset = (*InternalReleaseImageTLSSecret)(nil)

// InternalReleaseImageTLSSecret is the constant to represent contents of machine_configservertlssecret.yaml.template file.
type InternalReleaseImageTLSSecret struct {
	FileList []*asset.File
}

// Dependencies returns all of the dependencies directly needed by the asset.
func (t *InternalReleaseImageTLSSecret) Dependencies() []asset.Asset {
	return []asset.Asset{
		&installconfig.InstallConfig{},
		&manifests.InternalReleaseImage{},
	}
}

// Name returns the human-friendly name of the asset.
func (t *InternalReleaseImageTLSSecret) Name() string {
	return "InternalReleaseImageTLSSecret"
}

// Generate generates the actual files by this asset.
func (t *InternalReleaseImageTLSSecret) Generate(_ context.Context, dependencies asset.Parents) error {
	installConfig := &installconfig.InstallConfig{}
	iri := &manifests.InternalReleaseImage{}

	dependencies.Get(installConfig, iri)

	if !installConfig.Config.EnabledFeatureGates().Enabled(features.FeatureGateNoRegistryClusterInstall) {
		return nil
	}

	// Skip if InternalReleaseImage manifest wasn't found.
	if len(iri.FileList) == 0 {
		return nil
	}

	fileName := internalReleaseImageTLSSecretFileName
	data, err := content.GetBootkubeTemplate(fileName)
	if err != nil {
		return err
	}
	t.FileList = []*asset.File{
		{
			Filename: filepath.Join(content.TemplateDir, fileName),
			Data:     data,
		},
	}
	return nil
}

// Files returns the files generated by the asset.
func (t *InternalReleaseImageTLSSecret) Files() []*asset.File {
	return t.FileList
}

// Load returns the asset from disk.
func (t *InternalReleaseImageTLSSecret) Load(f asset.FileFetcher) (bool, error) {
	file, err := f.FetchByName(filepath.Join(content.TemplateDir, internalReleaseImageTLSSecretFileName))
	if err != nil {
		if os.IsNotExist(err) {
			return false, nil
		}
		return false, err
	}
	t.FileList = []*asset.File{file}
	return true, nil
}
