package bootkube

import (
	"os"
	"path/filepath"

	"github.com/openshift/installer/pkg/asset"
	"github.com/openshift/installer/pkg/asset/templates/content"
)

const (
	kubeSystemSecretEtcdMetricsServerFileName = "kube-system-secret-etcd-metrics-server.yaml.template"
)

var _ asset.WritableAsset = (*KubeSystemSecretEtcdMetricsServer)(nil)

// KubeSystemSecretEtcdMetricsServer is the constant to represent contents of  kube-system-secret-etcd-metrics-server.yaml.template file.
type KubeSystemSecretEtcdMetricsServer struct {
	FileList []*asset.File
}

// Dependencies returns all of the dependencies directly needed by the asset
func (t *KubeSystemSecretEtcdMetricsServer) Dependencies() []asset.Asset {
	return []asset.Asset{}
}

// Name returns the human-friendly name of the asset.
func (t *KubeSystemSecretEtcdMetricsServer) Name() string {
	return "KubeSystemSecretEtcdMetricsServer"
}

// Generate generates the actual files by this asset
func (t *KubeSystemSecretEtcdMetricsServer) Generate(parents asset.Parents) error {
	fileName := kubeSystemSecretEtcdMetricsServerFileName
	data, err := content.GetBootkubeTemplate(fileName)
	if err != nil {
		return err
	}
	t.FileList = []*asset.File{
		{
			Filename: filepath.Join(content.TemplateDir, fileName),
			Data:     []byte(data),
		},
	}
	return nil
}

// Files returns the files generated by the asset.
func (t *KubeSystemSecretEtcdMetricsServer) Files() []*asset.File {
	return t.FileList
}

// Load returns the asset from disk.
func (t *KubeSystemSecretEtcdMetricsServer) Load(f asset.FileFetcher) (bool, error) {
	file, err := f.FetchByName(filepath.Join(content.TemplateDir, kubeSystemSecretEtcdMetricsServerFileName))
	if err != nil {
		if os.IsNotExist(err) {
			return false, nil
		}
		return false, err
	}
	t.FileList = []*asset.File{file}
	return true, nil
}
