package bootkube

import (
	"os"
	"path/filepath"

	"github.com/openshift/installer/pkg/asset"
	"github.com/openshift/installer/pkg/asset/templates/content"
)

const (
	openshiftServiceCASignerSecretFileName = "openshift-service-ca-signer-secret.yaml.template"
)

var _ asset.WritableAsset = (*OpenshiftServiceCASignerSecret)(nil)

// OpenshiftServiceCASignerSecret is the constant to represent the contents of openshift-service-ca-signer-secret.yaml.template
type OpenshiftServiceCASignerSecret struct {
	FileList []*asset.File
}

// Dependencies returns all of the dependencies directly needed by the asset
func (t *OpenshiftServiceCASignerSecret) Dependencies() []asset.Asset {
	return []asset.Asset{}
}

// Name returns the human-friendly name of the asset.
func (t *OpenshiftServiceCASignerSecret) Name() string {
	return "OpenshiftServiceCASignerSecret"
}

// Generate generates the actual files by this asset
func (t *OpenshiftServiceCASignerSecret) Generate(parents asset.Parents) error {
	fileName := openshiftServiceCASignerSecretFileName
	data, err := content.GetBootkubeTemplate(fileName)
	if err != nil {
		return err
	}
	t.FileList = []*asset.File{
		{
			Filename: filepath.Join(content.TemplateDir, fileName),
			Data:     []byte(data),
		},
	}
	return nil
}

// Files returns the files generated by the asset.
func (t *OpenshiftServiceCASignerSecret) Files() []*asset.File {
	return t.FileList
}

// Load returns the asset from disk.
func (t *OpenshiftServiceCASignerSecret) Load(f asset.FileFetcher) (bool, error) {
	file, err := f.FetchByName(filepath.Join(content.TemplateDir, openshiftServiceCASignerSecretFileName))
	if err != nil {
		if os.IsNotExist(err) {
			return false, nil
		}
		return false, err
	}
	t.FileList = []*asset.File{file}
	return true, nil
}
