package bootkube

import (
	"os"
	"path/filepath"

	"github.com/openshift/installer/pkg/asset"
	"github.com/openshift/installer/pkg/asset/templates/content"
)

const (
	openShiftKubeAPIServerOperatorConfigmapUnsupportedCertRotationFileName = "openshift-kube-apiserver-operator-configmap-unsupported-cert-rotation-config.yaml.template"
)

var _ asset.WritableAsset = (*OpenShiftKubeAPIServerOperatorConfigmapUnsupportedCertRotation)(nil)

// OpenShiftKubeAPIServerOperatorConfigmapUnsupportedCertRotation is the constant to represent contents of openshift-kube-apiserver-operator-configmap-cert-rotation.yaml file
type OpenShiftKubeAPIServerOperatorConfigmapUnsupportedCertRotation struct {
	FileList []*asset.File
}

// Dependencies returns all of the dependencies directly needed by the asset
func (t *OpenShiftKubeAPIServerOperatorConfigmapUnsupportedCertRotation) Dependencies() []asset.Asset {
	return []asset.Asset{}
}

// Name returns the human-friendly name of the asset.
func (t *OpenShiftKubeAPIServerOperatorConfigmapUnsupportedCertRotation) Name() string {
	return "OpenShiftKubeAPIServerOperatorConfigmapUnsupportedCertRotation"
}

// Generate generates the actual files by this asset
func (t *OpenShiftKubeAPIServerOperatorConfigmapUnsupportedCertRotation) Generate(parents asset.Parents) error {
	return nil
}

// Files returns the files generated by the asset.
func (t *OpenShiftKubeAPIServerOperatorConfigmapUnsupportedCertRotation) Files() []*asset.File {
	return t.FileList
}

// Load returns the asset from disk.
func (t *OpenShiftKubeAPIServerOperatorConfigmapUnsupportedCertRotation) Load(f asset.FileFetcher) (bool, error) {
	file, err := f.FetchByName(filepath.Join(content.TemplateDir, openShiftKubeAPIServerOperatorConfigmapUnsupportedCertRotationFileName))
	if err != nil {
		if os.IsNotExist(err) {
			return false, nil
		}
		return false, err
	}
	t.FileList = []*asset.File{file}
	return true, nil
}
