package manifests

import (
	"encoding/base64"
	"fmt"
	"os"
	"path/filepath"

	corev1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"sigs.k8s.io/yaml"

	"github.com/openshift/installer/pkg/asset"
	"github.com/openshift/installer/pkg/asset/installconfig"
	"github.com/pkg/errors"
)

var (
	agentPullSecretName     = "pull-secret"
	agentPullSecretFilename = filepath.Join(manifestDir, fmt.Sprintf("%s.yaml", agentPullSecretName))
)

// AgentPullSecret generates the pull-secret file used by the agent installer.
type AgentPullSecret struct {
	File *asset.File
}

var _ asset.WritableAsset = (*AgentPullSecret)(nil)

// Name returns a human friendly name for the asset.
func (*AgentPullSecret) Name() string {
	return "Agent PullSecret"
}

// Dependencies returns all of the dependencies directly needed to generate
// the asset.
func (*AgentPullSecret) Dependencies() []asset.Asset {
	return []asset.Asset{
		&installconfig.InstallConfig{},
	}
}

// Generate generates the InfraEnv manifest.
func (a *AgentPullSecret) Generate(dependencies asset.Parents) error {

	installConfigAsset := &installconfig.InstallConfig{}
	dependencies.Get(installConfigAsset)

	secret := &corev1.Secret{
		TypeMeta: metav1.TypeMeta{
			APIVersion: "v1",
			Kind:       "Secret",
		},
		ObjectMeta: metav1.ObjectMeta{
			Name:      a.ResourceName(),
			Namespace: installConfigAsset.Config.Namespace,
		},
		StringData: map[string]string{
			".dockerconfigjson": base64.StdEncoding.EncodeToString([]byte(installConfigAsset.Config.PullSecret)),
		},
	}

	secretData, err := yaml.Marshal(secret)
	if err != nil {
		return errors.Wrap(err, "failed to marshal agent secret")
	}

	a.File = &asset.File{
		Filename: agentPullSecretFilename,
		Data:     secretData,
	}

	return nil
}

// Files returns the files generated by the asset.
func (a *AgentPullSecret) Files() []*asset.File {
	if a.File != nil {
		return []*asset.File{a.File}
	}
	return []*asset.File{}
}

// Load returns the asset from disk.
func (a *AgentPullSecret) Load(f asset.FileFetcher) (bool, error) {
	agentPullSecretFile, err := f.FetchByName(agentPullSecretFilename)
	if err != nil {
		if os.IsNotExist(err) {
			return false, nil
		}
		return false, errors.Wrap(err, fmt.Sprintf("failed to load %s file", agentPullSecretFilename))
	}

	a.File = agentPullSecretFile
	return true, nil
}

func (a *AgentPullSecret) ResourceName() string {
	return agentPullSecretName
}
