package manifests

import (
	"path/filepath"

	"github.com/pkg/errors"

	"github.com/openshift/installer/pkg/asset"
	"github.com/openshift/installer/pkg/asset/installconfig"
)

const (
	manifestDir = "manifests"
)

var (
	_ asset.WritableAsset = (*AgentManifests)(nil)
)

type AgentManifests struct {
	FileList []*asset.File
}

func (m *AgentManifests) Name() string {
	return "Agent Manifests"
}

func (m *AgentManifests) Dependencies() []asset.Asset {
	return []asset.Asset{
		&installconfig.ClusterID{},
		&installconfig.InstallConfig{},
		&InfraEnv{},
	}
}

func (m *AgentManifests) Generate(dependencies asset.Parents) error {
	infraEnv := &InfraEnv{}
	dependencies.Get(infraEnv)

	m.FileList = append(m.FileList, infraEnv.Files()...)
	asset.SortFiles(m.FileList)

	return nil
}

// Files returns the files generated by the asset.
func (m *AgentManifests) Files() []*asset.File {
	return m.FileList
}

// Load returns the manifests asset from disk.
func (m *AgentManifests) Load(f asset.FileFetcher) (bool, error) {
	fileList, err := f.FetchByPattern(filepath.Join(manifestDir, "*.yml"))
	if err != nil {
		return false, errors.Wrap(err, "failed to load *.yaml files")
	}

	if len(fileList) == 0 {
		return false, nil
	}

	m.FileList = fileList
	asset.SortFiles(m.FileList)

	return true, nil
}
