package manifests

import (
	"context"
	"path/filepath"

	"github.com/pkg/errors"

	"github.com/openshift/installer/pkg/asset"
)

const (
	openshiftManifestDir = "openshift"
)

// ExtraManifests manages the additional manifests for cluster customization
type ExtraManifests struct {
	FileList []*asset.File
}

var (
	_ asset.WritableAsset = (*ExtraManifests)(nil)
)

// Name returns a human friendly name for the operator
func (em *ExtraManifests) Name() string {
	return "Extra Manifests"
}

// Dependencies returns all of the dependencies directly needed by the
// Master asset
func (em *ExtraManifests) Dependencies() []asset.Asset {
	return []asset.Asset{}
}

// Generate is not required for ExtraManifests.
func (em *ExtraManifests) Generate(_ context.Context, dependencies asset.Parents) error {
	return nil
}

// Files returns the files generated by the asset.
func (em *ExtraManifests) Files() []*asset.File {
	return em.FileList
}

// Load reads the asset files from disk.
func (em *ExtraManifests) Load(f asset.FileFetcher) (found bool, err error) {
	yamlFileList, err := f.FetchByPattern(filepath.Join(openshiftManifestDir, "*.yaml"))
	if err != nil {
		return false, errors.Wrap(err, "failed to load *.yaml files")
	}
	ymlFileList, err := f.FetchByPattern(filepath.Join(openshiftManifestDir, "*.yml"))
	if err != nil {
		return false, errors.Wrap(err, "failed to load *.yml files")
	}

	em.FileList = append(em.FileList, yamlFileList...)
	em.FileList = append(em.FileList, ymlFileList...)
	asset.SortFiles(em.FileList)

	return len(em.FileList) > 0, nil
}

// OpenshiftManifestDir returns the name of directory to add extra manifests.
func OpenshiftManifestDir() string {
	return openshiftManifestDir
}
