package manifests

import (
	"context"
	"fmt"
	"os"
	"path/filepath"

	"github.com/pkg/errors"
	"github.com/sirupsen/logrus"
	goyaml "gopkg.in/yaml.v2"
	k8syaml "sigs.k8s.io/yaml"

	"github.com/openshift/installer/pkg/asset"
	"github.com/openshift/installer/pkg/asset/agent"
	"github.com/openshift/installer/pkg/asset/agent/workflow"
	"github.com/openshift/installer/pkg/types"
)

var fencingCredentialsFilename = filepath.Join(clusterManifestDir, "fencing-credentials.yaml")

// FencingCredentialsConfig represents the structure of the fencing-credentials.yaml file.
type FencingCredentialsConfig struct {
	// Credentials contains the list of fencing credentials for TNF clusters.
	Credentials []*types.Credential `yaml:"credentials"`
}

// FencingCredentials generates the fencing-credentials.yaml file for TNF clusters.
// This file contains BMC credentials for each control plane node, used by
// assisted-service to configure Pacemaker fencing.
type FencingCredentials struct {
	File   *asset.File
	Config *FencingCredentialsConfig
}

var _ asset.WritableAsset = (*FencingCredentials)(nil)

// Name returns a human friendly name for the asset.
func (*FencingCredentials) Name() string {
	return "Fencing Credentials"
}

// Dependencies returns all of the dependencies directly needed to generate
// the asset.
func (*FencingCredentials) Dependencies() []asset.Asset {
	return []asset.Asset{
		&workflow.AgentWorkflow{},
		&agent.OptionalInstallConfig{},
	}
}

// Generate generates the FencingCredentials manifest for TNF clusters.
func (f *FencingCredentials) Generate(_ context.Context, dependencies asset.Parents) error {
	agentWorkflow := &workflow.AgentWorkflow{}
	installConfig := &agent.OptionalInstallConfig{}
	dependencies.Get(agentWorkflow, installConfig)

	switch agentWorkflow.Workflow {
	case workflow.AgentWorkflowTypeInstall:
		// Fencing credentials are only applicable for install workflow
		if installConfig.Config == nil {
			return nil
		}

		if installConfig.Config.ControlPlane == nil || installConfig.Config.ControlPlane.Fencing == nil {
			return nil
		}

		credentials := installConfig.Config.ControlPlane.Fencing.Credentials
		if len(credentials) == 0 {
			return nil
		}

		logrus.Debugf("Generating fencing credentials file with %d credentials", len(credentials))

		f.Config = &FencingCredentialsConfig{
			Credentials: credentials,
		}

	case workflow.AgentWorkflowTypeAddNodes:
		// Fencing credentials are not applicable for add-nodes workflow
		// Day2 operations don't need fencing configuration
		return nil

	default:
		return fmt.Errorf("AgentWorkflowType value not supported: %s", agentWorkflow.Workflow)
	}

	return f.finish()
}

// Files returns the files generated by the asset.
func (f *FencingCredentials) Files() []*asset.File {
	if f.File != nil {
		return []*asset.File{f.File}
	}
	return []*asset.File{}
}

// Load returns the asset from disk.
func (f *FencingCredentials) Load(fetcher asset.FileFetcher) (bool, error) {
	file, err := fetcher.FetchByName(fencingCredentialsFilename)
	if err != nil {
		if os.IsNotExist(err) {
			return false, nil
		}
		return false, errors.Wrap(err, fmt.Sprintf("failed to load %s file", fencingCredentialsFilename))
	}

	config := &FencingCredentialsConfig{}
	if err := k8syaml.UnmarshalStrict(file.Data, config); err != nil {
		return false, errors.Wrapf(err, "failed to unmarshal %s", fencingCredentialsFilename)
	}

	f.Config = config
	f.File = file
	return true, nil
}

func (f *FencingCredentials) finish() error {
	if f.Config == nil {
		// No fencing configuration - this is valid for non-TNF clusters
		return nil
	}

	// Use gopkg.in/yaml.v2 for marshaling to respect YAML struct tags (lowercase field names).
	// This is critical for compatibility with assisted-service, which expects lowercase keys.
	data, err := goyaml.Marshal(f.Config)
	if err != nil {
		return errors.Wrapf(err, "failed to marshal %d fencing credentials", len(f.Config.Credentials))
	}

	f.File = &asset.File{
		Filename: fencingCredentialsFilename,
		Data:     data,
	}

	logrus.Debugf("Generated fencing credentials file at %s", fencingCredentialsFilename)
	return nil
}
