package manifests

import (
	"context"
	"fmt"
	"os"

	"github.com/pkg/errors"
	"github.com/sirupsen/logrus"
	"k8s.io/apimachinery/pkg/util/validation/field"

	aiv1beta1 "github.com/openshift/assisted-service/api/v1beta1"
	"github.com/openshift/assisted-service/models"
	"github.com/openshift/installer/pkg/asset"
	"github.com/openshift/installer/pkg/asset/agent/manifests/staticnetworkconfig"
)

// NMStateConfigFile takes care of just loading the nmstateconfig configuration file from the disk.
type NMStateConfigFile struct {
	File                *asset.File
	StaticNetworkConfig []*models.HostStaticNetworkConfig
	Config              []*aiv1beta1.NMStateConfig
}

var _ asset.WritableAsset = (*NMStateConfigFile)(nil)

// Name returns a human friendly name for the asset.
func (*NMStateConfigFile) Name() string {
	return "NMState Config File"
}

// Dependencies returns all of the dependencies directly needed to generate
// the asset.
func (*NMStateConfigFile) Dependencies() []asset.Asset {
	return []asset.Asset{}
}

// Generate is not used for this asset. Returns empty config when file not found.
func (n *NMStateConfigFile) Generate(_ context.Context, dependencies asset.Parents) error {
	// For unconfigured-ignition workflow, nmstateconfig.yaml is optional.
	// Return empty config when file is not on disk.
	n.Config = []*aiv1beta1.NMStateConfig{}
	n.StaticNetworkConfig = []*models.HostStaticNetworkConfig{}
	n.File = nil
	return nil
}

// Files returns the files generated by the asset.
func (n *NMStateConfigFile) Files() []*asset.File {
	if n.File != nil {
		return []*asset.File{n.File}
	}
	return []*asset.File{}
}

// Load returns the NMStateConfig asset from the disk.
func (n *NMStateConfigFile) Load(f asset.FileFetcher) (bool, error) {
	file, err := f.FetchByName(nmStateConfigFilename)
	if err != nil {
		if os.IsNotExist(err) {
			return false, nil
		}
		return false, errors.Wrapf(err, "failed to load file %s", nmStateConfigFilename)
	}

	// Split up the file into multiple YAMLs if it contains NMStateConfig for more than one node
	yamlList, err := GetMultipleYamls[aiv1beta1.NMStateConfig](file.Data)
	if err != nil {
		return false, errors.Wrapf(err, "could not decode YAML for %s", nmStateConfigFilename)
	}

	var staticNetworkConfig []*models.HostStaticNetworkConfig
	var nmStateConfigList []*aiv1beta1.NMStateConfig

	for i := range yamlList {
		nmStateConfig := yamlList[i]
		staticNetworkConfig = append(staticNetworkConfig, &models.HostStaticNetworkConfig{
			MacInterfaceMap: buildMacInterfaceMap(nmStateConfig),
			NetworkYaml:     string(nmStateConfig.Spec.NetConfig.Raw),
		})
		nmStateConfigList = append(nmStateConfigList, &nmStateConfig)
	}

	n.File, n.StaticNetworkConfig, n.Config = file, staticNetworkConfig, nmStateConfigList
	if err = n.finish(); err != nil {
		return false, err
	}
	return true, nil
}

func (n *NMStateConfigFile) finish() error {
	if err := n.validateWithNMStateCtl(); err != nil {
		return err
	}

	if errList := n.validateNMStateConfig().ToAggregate(); errList != nil {
		return errors.Wrapf(errList, "invalid NMStateConfig configuration")
	}
	return nil
}

func (n *NMStateConfigFile) validateWithNMStateCtl() error {
	level := logrus.GetLevel()
	logrus.SetLevel(logrus.WarnLevel)
	staticNetworkConfigGenerator := staticnetworkconfig.New(logrus.WithField("pkg", "manifests"), staticnetworkconfig.Config{MaxConcurrentGenerations: 2})
	defer logrus.SetLevel(level)

	// Validate the network config using nmstatectl
	if err := staticNetworkConfigGenerator.ValidateStaticConfigParams(context.Background(), n.StaticNetworkConfig); err != nil {
		return errors.Wrapf(err, "staticNetwork configuration is not valid")
	}
	return nil
}

func (n *NMStateConfigFile) validateNMStateConfig() field.ErrorList {
	allErrs := field.ErrorList{}

	if err := n.validateNMStateLabels(); err != nil {
		allErrs = append(allErrs, err...)
	}

	return allErrs
}

func (n *NMStateConfigFile) validateNMStateLabels() field.ErrorList {
	var allErrs field.ErrorList

	fieldPath := field.NewPath("labels")

	for _, nmStateConfig := range n.Config {
		if len(nmStateConfig.ObjectMeta.Labels) == 0 {
			allErrs = append(allErrs, field.Required(fieldPath, fmt.Sprintf("%s does not have any label set", nmStateConfig.Name)))
		}
	}

	return allErrs
}
