package configimage

import (
	"context"
	"errors"
	"fmt"
	"os"
	"path/filepath"

	"github.com/openshift/assisted-image-service/pkg/isoeditor"
	"github.com/openshift/installer/pkg/asset"
	"github.com/openshift/installer/pkg/types/imagebased"
)

const (
	configImageFilename = "imagebasedconfig.iso"
	configImageLabel    = imagebased.BlockDeviceLabel

	clusterConfigurationDir = "cluster-configuration"
	extraManifestsDir       = "extra-manifests"
)

var (
	manifestsDir = filepath.Join(clusterConfigurationDir, "manifests")
)

// ConfigImage is an asset that generates a configuration ISO that can be used to
// configure image-based installer provisioned hosts.
type ConfigImage struct {
	tmpPath string
}

var _ asset.WritableAsset = (*ConfigImage)(nil)

// Dependencies returns the assets on which the Config asset depends.
func (ci *ConfigImage) Dependencies() []asset.Asset {
	return []asset.Asset{
		&ClusterConfiguration{},
		&ImageDigestSources{},
		&ExtraManifests{},
	}
}

// Generate generates the configuration image file.
func (ci *ConfigImage) Generate(_ context.Context, dependencies asset.Parents) error {
	// Save the image to a temp file
	tmpPath, err := os.MkdirTemp("", "imagebased")
	if err != nil {
		return fmt.Errorf("could not create temp directory: %w", err)
	}
	ci.tmpPath = tmpPath

	dirs := []string{
		clusterConfigurationDir,
		manifestsDir,
		extraManifestsDir,
	}
	for _, dir := range dirs {
		if err := os.MkdirAll(filepath.Join(ci.tmpPath, dir), 0755); err != nil {
			return fmt.Errorf("could not create %s directory: %w", dir, err)
		}
	}

	createFile := func(file *asset.File) error {
		f, err := os.Create(filepath.Join(ci.tmpPath, file.Filename))
		if err != nil {
			return fmt.Errorf("could not create %s: %w", file.Filename, err)
		}
		defer f.Close()

		if _, err := f.Write(file.Data); err != nil {
			return fmt.Errorf("could not write %s: %w", file.Filename, err)
		}
		return nil
	}

	for _, a := range []asset.WritableAsset{
		&ClusterConfiguration{},
		&ImageDigestSources{},
		&ExtraManifests{},
	} {
		dependencies.Get(a)

		for _, file := range a.Files() {
			if err := createFile(file); err != nil {
				return err
			}
		}
	}

	return nil
}

// PersistToFile writes the iso image in the assets folder.
func (ci *ConfigImage) PersistToFile(directory string) error {
	defer os.RemoveAll(ci.tmpPath)

	// If the tmpPath is not set then it means that either one of the Config
	// dependencies or the asset itself failed for some reason
	if ci.tmpPath == "" {
		return errors.New("cannot generate Config image due to configuration errors")
	}

	configImageFile := filepath.Join(directory, configImageFilename)

	// Remove symlink if it exists
	os.Remove(configImageFile)

	err := isoeditor.Create(configImageFile, ci.tmpPath, configImageLabel)
	if err != nil {
		return err
	}

	return nil
}

// Name returns the human-friendly name of the asset.
func (ci *ConfigImage) Name() string {
	return "Image-based Installer Config ISO"
}

// Load returns the ISO from disk.
func (ci *ConfigImage) Load(f asset.FileFetcher) (bool, error) {
	// The ISO will not be needed by another asset so load is noop.
	// This is implemented because it is required by WritableAsset
	return false, nil
}

// Files returns the files generated by the asset.
func (ci *ConfigImage) Files() []*asset.File {
	// Return empty array because File will never be loaded.
	return []*asset.File{}
}
