package configimage

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"os"
	"path/filepath"

	k8sjson "sigs.k8s.io/json"

	"github.com/openshift/installer/pkg/asset"
	"github.com/openshift/installer/pkg/types"
)

var (
	imageDigestSourcesFilename = filepath.Join(manifestsDir, "image-digest-sources.json")

	_ asset.WritableAsset = (*ImageDigestSources)(nil)
)

// ImageDigestSources generates the image-based installer image digest sources asset.
type ImageDigestSources struct {
	File   *asset.File
	Config []types.ImageDigestSource
}

// Name returns a human friendly name for the asset.
func (*ImageDigestSources) Name() string {
	return "Image-based installer image digest sources"
}

// Dependencies returns all of the dependencies directly needed to generate
// the asset.
func (*ImageDigestSources) Dependencies() []asset.Asset {
	return []asset.Asset{
		&InstallConfig{},
	}
}

// Generate generates the Image-based Installer ImageDigestSources manifest.
func (ids *ImageDigestSources) Generate(_ context.Context, dependencies asset.Parents) error {
	installConfig := &InstallConfig{}

	dependencies.Get(installConfig)

	if installConfig.Config == nil || installConfig.Config.ImageDigestSources == nil {
		return nil
	}

	ids.Config = installConfig.Config.ImageDigestSources

	imageDigestSourcesData, err := json.Marshal(ids.Config)
	if err != nil {
		return fmt.Errorf("failed to marshal image-based installer ImageDigestSources: %w", err)
	}

	ids.File = &asset.File{
		Filename: imageDigestSourcesFilename,
		Data:     imageDigestSourcesData,
	}

	return ids.finish()
}

// Files returns the files generated by the asset.
func (ids *ImageDigestSources) Files() []*asset.File {
	if ids.File != nil {
		return []*asset.File{ids.File}
	}
	return []*asset.File{}
}

// Load returns ImageDigestSources asset from the disk.
func (ids *ImageDigestSources) Load(f asset.FileFetcher) (bool, error) {
	file, err := f.FetchByName(imageDigestSourcesFilename)
	if err != nil {
		if os.IsNotExist(err) {
			return false, nil
		}
		return false, fmt.Errorf("failed to load %s file: %w", imageDigestSourcesFilename, err)
	}

	config := []types.ImageDigestSource{}
	strErrs, err := k8sjson.UnmarshalStrict(file.Data, &config)
	if len(strErrs) > 0 {
		return false, fmt.Errorf("failed to unmarshal %s: %w", imageDigestSourcesFilename, errors.Join(strErrs...))
	}
	if err != nil {
		return false, fmt.Errorf("failed to unmarshal %s: invalid JSON syntax", imageDigestSourcesFilename)
	}

	ids.File, ids.Config = file, config
	if err = ids.finish(); err != nil {
		return false, err
	}

	return true, nil
}

func (ids *ImageDigestSources) finish() error {
	if ids.Config == nil {
		return errors.New("missing configuration or manifest file")
	}
	return nil
}
