apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: openshiftdockerregistries.dockerregistry.operator.openshift.io
spec:
  group: dockerregistry.operator.openshift.io
  names:
    kind: OpenShiftDockerRegistry
    listKind: OpenShiftDockerRegistryList
    plural: openshiftdockerregistries
    singular: openshiftdockerregistry
  scope: Namespaced
  version: v1alpha1
