apiVersion: v1
kind: Service
metadata:
  name: tectonic-console
  labels:
    app: tectonic-console
    component: ui
spec:
  selector:
    app: tectonic-console
    component: ui
  type: NodePort
  ports:
  - name: tectonic-console
    protocol: TCP
    port: 80
