[[constraint]]
  name = "k8s.io/client-go"
  version = "4.0.0-beta.0"

[[constraint]]
  name = "k8s.io/kubernetes"
  version = "1.7.0"

[prune]
  non-go = true
  go-tests = true
  unused-packages = true
