apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-config-v1
  namespace: tectonic-system
data:
  utility-config: |
    apiVersion: v1
    kind: UtilityConfig
    identityConfig:
      adminEmail: ${admin_email}
      adminPasswordHash: ${admin_password_hash}
      adminUserID: ${admin_user_id}
      consoleClientID: ${console_client_id}
      consoleSecret: ${console_secret}
      kubectlClientID: ${kubectl_client_id}
      kubectlSecret: ${kubectl_secret}
    ingressConfig:
      consoleBaseHost: ${console_base_host}
      ingressKind: ${ingress_kind}
    statsEmitterConfig:
      statsURL: ${stats_url}
    tectonicConfigMap:
      baseAddress: ${base_address}
      certificatesStrategy: ${certificates_strategy}
      clusterID: ${cluster_id}
      clusterName: ${cluster_name}
      identityAPIService: ${identity_api_service}
      installerPlatform: ${platform}
      kubeAPIserverURL: ${kube_apiserver_url}
      tectonicVersion: ${tectonic_version}
  addon-config: |
      apiVersion: v1
      kind: AddonConfig
      heapsterConfig:
      dnsConfig:
          clusterIP: ${kube_dns_service_ip}
      cloudProvider: ${platform}
  network-config: |
      apiVersion: v1
      kind: NetworkConfig
      ${network_config}
