package tls

import (
	"context"

	"github.com/openshift/installer/pkg/asset"
	"github.com/openshift/installer/pkg/asset/installconfig"
	"github.com/openshift/installer/pkg/types/baremetal"
)

// BMCVerifyCA is the asset for the user-provided BMC verify CA certificate file.
// This CA certificate is used to verify BMC TLS certificates.
type BMCVerifyCA struct {
	File *asset.File
}

var _ asset.WritableAsset = (*BMCVerifyCA)(nil)

// Name returns the human-friendly name of the asset.
func (*BMCVerifyCA) Name() string {
	return "BMC Verify CA Certificate"
}

// Dependencies returns the dependency of the asset.
func (*BMCVerifyCA) Dependencies() []asset.Asset {
	return []asset.Asset{
		&installconfig.InstallConfig{},
	}
}

// Generate generates the BMC verify CA file from the install config.
func (a *BMCVerifyCA) Generate(_ context.Context, dependencies asset.Parents) error {
	installConfig := &installconfig.InstallConfig{}
	dependencies.Get(installConfig)

	// Only generate the file for baremetal platform with BMCVerifyCA configured
	if installConfig.Config.Platform.Name() != baremetal.Name {
		return nil
	}

	if installConfig.Config.Platform.BareMetal == nil || installConfig.Config.Platform.BareMetal.BMCVerifyCA == "" {
		return nil
	}

	// Create the file at rootDir/bmc-ca/verify_ca.crt (rootDir = /opt/openshift)
	a.File = &asset.File{
		Filename: "bmc-ca/verify_ca.crt",
		Data:     []byte(installConfig.Config.Platform.BareMetal.BMCVerifyCA),
	}

	return nil
}

// Files returns the files generated by the asset.
func (a *BMCVerifyCA) Files() []*asset.File {
	if a.File != nil {
		return []*asset.File{a.File}
	}
	return []*asset.File{}
}

// Load loads the already-generated files back from disk.
func (a *BMCVerifyCA) Load(f asset.FileFetcher) (bool, error) {
	return false, nil
}
