package tls

import (
	"context"
	"crypto/rand"
	"crypto/rsa"
	"fmt"
	"os"

	"github.com/sirupsen/logrus"

	"github.com/openshift/installer/pkg/asset"
	"github.com/openshift/installer/pkg/asset/installconfig"
	awstypes "github.com/openshift/installer/pkg/types/aws"
)

const (
	boundSASigningKeyFileName = "bound-service-account-signing-key.key"
	boundSASigningPubFileName = "bound-service-account-signing-key.pub"
)

// BoundSASigningKey contains the key and public parts for the
// service account signing key used by kube-apiserver.
// When AWS STS is configured in managed mode, this asset generates
// a 4096-bit RSA key pair. Otherwise, it only loads user-provided
// keys from disk.
type BoundSASigningKey struct {
	FileList []*asset.File
}

var _ asset.WritableAsset = (*BoundSASigningKey)(nil)

// Name returns a human friendly name for the asset.
func (*BoundSASigningKey) Name() string {
	return "Service Account Signing key"
}

// Dependencies returns all of the dependencies directly needed to generate
// the asset.
func (*BoundSASigningKey) Dependencies() []asset.Asset {
	return []asset.Asset{
		&installconfig.InstallConfig{},
	}
}

// Generate generates a 4096-bit RSA key pair when AWS STS managed mode
// is active. Otherwise it is a no-op (user-provided keys are handled by Load).
func (sk *BoundSASigningKey) Generate(_ context.Context, dependencies asset.Parents) error {
	ic := &installconfig.InstallConfig{}
	dependencies.Get(ic)

	switch ic.Config.Platform.Name() {
	case awstypes.Name:
		// Generating SA signing key is only supported when STS resources are managed.
		if !ic.Config.Platform.AWS.IsSTSManaged() {
			return nil
		}
	default:
		logrus.Debugf("Skipped generating Service Account Signing key for unsupported platform %s", ic.Config.Platform.Name())
		return nil
	}

	key, err := rsa.GenerateKey(rand.Reader, 4096)
	if err != nil {
		return fmt.Errorf("failed to generate RSA key for service account signing: %w", err)
	}

	privData := PrivateKeyToPem(key)
	pubData, err := PublicKeyToPem(&key.PublicKey)
	if err != nil {
		return fmt.Errorf("failed to encode public key: %w", err)
	}

	sk.FileList = []*asset.File{
		{Filename: assetFilePath(boundSASigningKeyFileName), Data: privData},
		{Filename: assetFilePath(boundSASigningPubFileName), Data: pubData},
	}

	return nil
}

// Files returns the files generated by the asset.
func (sk *BoundSASigningKey) Files() []*asset.File {
	return sk.FileList
}

// PublicKeyData returns the PEM-encoded public key bytes, or nil
// if the key has not been generated or loaded.
func (sk *BoundSASigningKey) PublicKeyData() []byte {
	for _, f := range sk.FileList {
		if f.Filename == assetFilePath(boundSASigningPubFileName) {
			return f.Data
		}
	}
	return nil
}

// Load reads the private key from the disk.
// It ensures that the key provided is a valid RSA key.
func (sk *BoundSASigningKey) Load(f asset.FileFetcher) (bool, error) {
	keyFile, err := f.FetchByName(assetFilePath(boundSASigningKeyFileName))
	if err != nil {
		if os.IsNotExist(err) {
			return false, nil
		}
		return false, err
	}

	rsaKey, err := PemToPrivateKey(keyFile.Data)
	if err != nil {
		logrus.Debugf("Failed to load rsa.PrivateKey from file: %s", err)
		return false, fmt.Errorf("failed to load rsa.PrivateKey from the file: %w", err)
	}
	pubData, err := PublicKeyToPem(&rsaKey.PublicKey)
	if err != nil {
		return false, fmt.Errorf("failed to extract public key from the key: %w", err)
	}
	sk.FileList = []*asset.File{keyFile, {Filename: assetFilePath(boundSASigningPubFileName), Data: pubData}}
	return true, nil
}
