package permissions

import (
	"context"
	"encoding/json"
	"fmt"

	iamv1 "sigs.k8s.io/cluster-api-provider-aws/v2/iam/api/v1beta1"

	"github.com/openshift/installer/pkg/asset"
	"github.com/openshift/installer/pkg/asset/installconfig"
	awsconfig "github.com/openshift/installer/pkg/asset/installconfig/aws"
	"github.com/openshift/installer/pkg/types/aws"
)

const (
	awsPolicyMintFilename        = "aws-permissions-policy-mint-creds.json"
	awsPolicyPassthroughFilename = "aws-permissions-policy-passthrough-creds.json"
)

// Permissions has the permissions needed for a given cluster configuration.
type Permissions struct {
	FileList []*asset.File
}

var _ asset.WritableAsset = (*Permissions)(nil)

// Name returns a human friendly name for the asset.
func (o *Permissions) Name() string {
	return "Permissions"
}

// Dependencies returns all of the dependencies directly needed by the Permissions asset.
func (o *Permissions) Dependencies() []asset.Asset {
	return []asset.Asset{
		&installconfig.InstallConfig{},
	}
}

// Generate generates the respective operator config.yml files.
func (o *Permissions) Generate(ctx context.Context, dependencies asset.Parents) error {
	ic := &installconfig.InstallConfig{}
	dependencies.Get(ic)

	o.FileList = []*asset.File{}
	platform := ic.Config.Platform.Name()
	switch platform {
	case aws.Name:
		reqGroups := awsconfig.RequiredPermissionGroups(ic.Config)
		// Include permissions needed by CCO/cluster for mint creds mode
		mintGroups := append([]awsconfig.PermissionGroup{awsconfig.PermissionMintCreds}, reqGroups...)
		if err := o.writePolicy(mintGroups, awsPolicyMintFilename); err != nil {
			return fmt.Errorf("failed to generate mint credentials permissions: %w", err)
		}
		// Include permissions needed by CCO/cluster for passthrough creds mode
		passGroups := append([]awsconfig.PermissionGroup{awsconfig.PermissionPassthroughCreds}, reqGroups...)
		if err := o.writePolicy(passGroups, awsPolicyPassthroughFilename); err != nil {
			return fmt.Errorf("failed to generate passthrough credentials permissions: %w", err)
		}
	default:
		return fmt.Errorf("platform %q does not support fine-grained permissions", platform)
	}

	return nil
}

func (o *Permissions) writePolicy(groups []awsconfig.PermissionGroup, filename string) error {
	perms, err := awsconfig.PermissionsList(groups)
	if err != nil {
		return fmt.Errorf("failed to generate permissions list: %w", err)
	}

	policy := iamv1.PolicyDocument{
		Version: "2012-10-17",
		Statement: []iamv1.StatementEntry{
			{
				Effect:   "Allow",
				Action:   perms,
				Resource: iamv1.Resources{"*"},
			},
		},
	}
	policyBytes, err := json.Marshal(policy)
	if err != nil {
		return fmt.Errorf("failed to marshal permissions policy: %w", err)
	}

	o.FileList = append(o.FileList, &asset.File{
		Filename: filename,
		Data:     policyBytes,
	})

	return nil
}

// Files returns the files generated by the asset.
func (o *Permissions) Files() []*asset.File {
	return o.FileList
}

// Load returns the openshift asset from disk.
func (o *Permissions) Load(f asset.FileFetcher) (bool, error) {
	return false, nil
}
