apiVersion: v1
kind: Namespace
metadata:
  labels:
    openshift.io/run-level: "0"
  name: openshift-core-operators
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: openshiftapiserveroperatorconfigs.openshiftapiserver.operator.openshift.io
spec:
  scope: Cluster
  group: openshiftapiserver.operator.openshift.io
  version: v1alpha1
  names:
    kind: OpenShiftAPIServerOperatorConfig
    plural: openshiftapiserveroperatorconfigs
    singular: openshiftapiserveroperatorconfig
    categories:
    - coreoperators
  subresources:
    status: {}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: system:openshift:operator:cluster-openshift-apiserver-operator
roleRef:
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  namespace: openshift-core-operators
  name: openshift-cluster-openshift-apiserver-operator
---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: openshift-core-operators
  name: openshift-cluster-openshift-apiserver-operator-config
data:
  config.yaml: |
    apiVersion: operator.openshift.io/v1alpha1
    kind: GenericOperatorConfig
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: openshift-core-operators
  name: openshift-cluster-openshift-apiserver-operator
  labels:
    app: openshift-cluster-openshift-apiserver-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: openshift-cluster-openshift-apiserver-operator
  template:
    metadata:
      name: openshift-cluster-openshift-apiserver-operator
      labels:
        app: openshift-cluster-openshift-apiserver-operator
    spec:
      serviceAccountName: openshift-cluster-openshift-apiserver-operator
      containers:
      - name: operator
        image: ${cluster_openshift_apiserver_operator_image}
        imagePullPolicy: IfNotPresent
        command: ["cluster-openshift-apiserver-operator", "operator"]
        args:
        - "--config=/var/run/configmaps/config/config.yaml"
        - "-v=4"
        volumeMounts:
        - mountPath: /var/run/configmaps/config
          name: config
      volumes:
      - name: serving-cert
        secret:
          defaultMode: 400
          secretName: openshift-cluster-openshift-apiserver-operator-serving-cert
          optional: true
      - name: config
        configMap:
          defaultMode: 440
          name: openshift-cluster-openshift-apiserver-operator-config
---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: openshift-core-operators
  name: openshift-cluster-openshift-apiserver-operator
  labels:
    app: openshift-cluster-openshift-apiserver-operator
---
apiVersion: openshiftapiserver.operator.openshift.io/v1alpha1
kind: OpenShiftAPIServerOperatorConfig
metadata:
  name: instance
spec:
  managementState: Managed
  imagePullSpec: openshift/origin-hypershift:latest
  version: 3.11.0
  logging:
    level: 4
  replicas: 2
