// Code generated by MockGen. DO NOT EDIT.
// Source: ./imageclient.go
//
// Generated by this command:
//
//	mockgen -source=./imageclient.go -destination=./mock/imageclient_generated.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
	compute "google.golang.org/api/compute/v1"
)

// MockImageClient is a mock of ImageClient interface.
type MockImageClient struct {
	ctrl     *gomock.Controller
	recorder *MockImageClientMockRecorder
	isgomock struct{}
}

// MockImageClientMockRecorder is the mock recorder for MockImageClient.
type MockImageClientMockRecorder struct {
	mock *MockImageClient
}

// NewMockImageClient creates a new mock instance.
func NewMockImageClient(ctrl *gomock.Controller) *MockImageClient {
	mock := &MockImageClient{ctrl: ctrl}
	mock.recorder = &MockImageClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockImageClient) EXPECT() *MockImageClientMockRecorder {
	return m.recorder
}

// CleanupStaging mocks base method.
func (m *MockImageClient) CleanupStaging(ctx context.Context, bucketName, objectName string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CleanupStaging", ctx, bucketName, objectName)
	ret0, _ := ret[0].(error)
	return ret0
}

// CleanupStaging indicates an expected call of CleanupStaging.
func (mr *MockImageClientMockRecorder) CleanupStaging(ctx, bucketName, objectName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CleanupStaging", reflect.TypeOf((*MockImageClient)(nil).CleanupStaging), ctx, bucketName, objectName)
}

// CreateImage mocks base method.
func (m *MockImageClient) CreateImage(ctx context.Context, projectID, imageName, gcsSource string, labels map[string]string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateImage", ctx, projectID, imageName, gcsSource, labels)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateImage indicates an expected call of CreateImage.
func (mr *MockImageClientMockRecorder) CreateImage(ctx, projectID, imageName, gcsSource, labels any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateImage", reflect.TypeOf((*MockImageClient)(nil).CreateImage), ctx, projectID, imageName, gcsSource, labels)
}

// CreateStagingBucket mocks base method.
func (m *MockImageClient) CreateStagingBucket(ctx context.Context, bucketName, projectID, region string, labels map[string]string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateStagingBucket", ctx, bucketName, projectID, region, labels)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateStagingBucket indicates an expected call of CreateStagingBucket.
func (mr *MockImageClientMockRecorder) CreateStagingBucket(ctx, bucketName, projectID, region, labels any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateStagingBucket", reflect.TypeOf((*MockImageClient)(nil).CreateStagingBucket), ctx, bucketName, projectID, region, labels)
}

// GetImage mocks base method.
func (m *MockImageClient) GetImage(ctx context.Context, projectID, imageName string) (*compute.Image, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetImage", ctx, projectID, imageName)
	ret0, _ := ret[0].(*compute.Image)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetImage indicates an expected call of GetImage.
func (mr *MockImageClientMockRecorder) GetImage(ctx, projectID, imageName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetImage", reflect.TypeOf((*MockImageClient)(nil).GetImage), ctx, projectID, imageName)
}

// UniverseDomain mocks base method.
func (m *MockImageClient) UniverseDomain(ctx context.Context) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UniverseDomain", ctx)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UniverseDomain indicates an expected call of UniverseDomain.
func (mr *MockImageClientMockRecorder) UniverseDomain(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UniverseDomain", reflect.TypeOf((*MockImageClient)(nil).UniverseDomain), ctx)
}

// UploadObject mocks base method.
func (m *MockImageClient) UploadObject(ctx context.Context, bucketName, objectName, filePath string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UploadObject", ctx, bucketName, objectName, filePath)
	ret0, _ := ret[0].(error)
	return ret0
}

// UploadObject indicates an expected call of UploadObject.
func (mr *MockImageClientMockRecorder) UploadObject(ctx, bucketName, objectName, filePath any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UploadObject", reflect.TypeOf((*MockImageClient)(nil).UploadObject), ctx, bucketName, objectName, filePath)
}
