// Code generated by ami_regions_generate.go; DO NOT EDIT.

package rhcos

// AMIRegionsAARCH64 is a list of regions where the RHEL CoreOS is published for architecture AARCH64.
var AMIRegionsAARCH64 = []string{
	"ap-east-1",
	"ap-northeast-1",
	"ap-northeast-2",
	"ap-south-1",
	"ap-southeast-1",
	"ap-southeast-2",
	"ca-central-1",
	"eu-central-1",
	"eu-south-1",
	"eu-west-1",
	"eu-west-2",
	"sa-east-1",
	"us-east-1",
	"us-east-2",
	"us-west-1",
	"us-west-2",
}
