package tectonic

import (
	"os"
	"path/filepath"

	"github.com/openshift/installer/pkg/asset"
	"github.com/openshift/installer/pkg/asset/templates/content"
)

const (
	kubeAddonOperatorFileName = "kube-addon-01-operator.yaml.template"
)

var _ asset.WritableAsset = (*KubeAddonOperator)(nil)

// KubeAddonOperator  is the variable/constant representing the contents of the respective file
type KubeAddonOperator struct {
	fileName string
	FileList []*asset.File
}

// Dependencies returns all of the dependencies directly needed by the asset
func (t *KubeAddonOperator) Dependencies() []asset.Asset {
	return []asset.Asset{}
}

// Name returns the human-friendly name of the asset.
func (t *KubeAddonOperator) Name() string {
	return "KubeAddonOperator"
}

// Generate generates the actual files by this asset
func (t *KubeAddonOperator) Generate(parents asset.Parents) error {
	t.fileName = kubeAddonOperatorFileName
	data, err := content.GetTectonicTemplate(t.fileName)
	if err != nil {
		return err
	}
	t.FileList = []*asset.File{
		{
			Filename: filepath.Join(content.TemplateDir, t.fileName),
			Data:     []byte(data),
		},
	}
	return nil
}

// Files returns the files generated by the asset.
func (t *KubeAddonOperator) Files() []*asset.File {
	return t.FileList
}

// Load returns the asset from disk.
func (t *KubeAddonOperator) Load(f asset.FileFetcher) (bool, error) {
	file, err := f.FetchByName(filepath.Join(content.TemplateDir, kubeAddonOperatorFileName))
	if err != nil {
		if os.IsNotExist(err) {
			return false, nil
		}
		return false, err
	}
	t.FileList = []*asset.File{file}
	return true, nil
}
