package openshift

import (
	"os"
	"path/filepath"

	"github.com/openshift/installer/pkg/asset"
	"github.com/openshift/installer/pkg/asset/templates/content"
)

const (
	baremetalCRDfilename = "baremetal-deployment-crd.yaml"
)

var _ asset.WritableAsset = (*BaremetalCRDs)(nil)

// BaremetalCRDs is the custom resource definitions for the baremetal deployment
type BaremetalCRDs struct {
	FileList []*asset.File
}

// Dependencies returns all of the dependencies directly needed by the asset
func (t *BaremetalCRDs) Dependencies() []asset.Asset {
	return []asset.Asset{}
}

// Name returns the human-friendly name of the asset.
func (t *BaremetalCRDs) Name() string {
	return "Baremetal CRDs"
}

// Generate generates the actual files by this asset
func (t *BaremetalCRDs) Generate(parents asset.Parents) error {
	data, err := content.GetOpenshiftTemplate(baremetalCRDfilename)
	if err != nil {
		return err
	}
	t.FileList = append(t.FileList, &asset.File{
		Filename: filepath.Join(content.TemplateDir, baremetalCRDfilename),
		Data:     []byte(data),
	})
	return nil
}

// Files returns the files generated by the asset.
func (t *BaremetalCRDs) Files() []*asset.File {
	return t.FileList
}

// Load returns the asset from disk.
func (t *BaremetalCRDs) Load(f asset.FileFetcher) (bool, error) {
	file, err := f.FetchByName(filepath.Join(content.TemplateDir, baremetalCRDfilename))
	if err != nil {
		if os.IsNotExist(err) {
			return false, nil
		}
		return false, err
	}
	t.FileList = append(t.FileList, file)

	return true, nil
}
