package openshift

import (
	"os"
	"path/filepath"

	"github.com/openshift/installer/pkg/asset"
	"github.com/openshift/installer/pkg/asset/templates/content"
)

const (
	fileName = "ignition-provisioning-secret.yaml.template"
)

var _ asset.WritableAsset = (*IgnitionProvisioningSecret)(nil)

// IgnitionProvisioningSecret implements https://github.com/openshift/enhancements/pull/443
type IgnitionProvisioningSecret struct {
	FileList []*asset.File
}

// Dependencies returns all of the dependencies directly needed by the asset
func (t *IgnitionProvisioningSecret) Dependencies() []asset.Asset {
	return []asset.Asset{}
}

// Name returns the human-friendly name of the asset.
func (t *IgnitionProvisioningSecret) Name() string {
	return "IgnitionProvisioningSecret"
}

// Generate generates the actual files by this asset
func (t *IgnitionProvisioningSecret) Generate(parents asset.Parents) error {
	data, err := content.GetOpenshiftTemplate(fileName)
	if err != nil {
		return err
	}
	t.FileList = []*asset.File{
		{
			Filename: filepath.Join(content.TemplateDir, fileName),
			Data:     []byte(data),
		},
	}
	return nil
}

// Files returns the files generated by the asset.
func (t *IgnitionProvisioningSecret) Files() []*asset.File {
	return t.FileList
}

// Load returns the asset from disk.
func (t *IgnitionProvisioningSecret) Load(f asset.FileFetcher) (bool, error) {
	file, err := f.FetchByName(filepath.Join(content.TemplateDir, fileName))
	if err != nil {
		if os.IsNotExist(err) {
			return false, nil
		}
		return false, err
	}
	t.FileList = []*asset.File{file}
	return true, nil
}
