package openshift

import (
	"context"
	"os"
	"path/filepath"

	"github.com/openshift/installer/pkg/asset"
	"github.com/openshift/installer/pkg/asset/templates/content"
	"github.com/sirupsen/logrus"
)

const (
	ironicVirtualMediaTLSCertTemplate = "ironic-virtualmedia-tls-cert.yaml.template"
	ironicVirtualMediaTLSKeyTemplate  = "ironic-virtualmedia-tls-key.yaml.template"
)

var _ asset.WritableAsset = (*IronicVirtualMediaTLS)(nil)

// IronicVirtualMediaTLS is the variable to represent contents of corresponding files.
type IronicVirtualMediaTLS struct {
	FileList []*asset.File
}

// Dependencies returns all of the dependencies directly needed by the asset.
func (t *IronicVirtualMediaTLS) Dependencies() []asset.Asset {
	return []asset.Asset{}
}

// Name returns the human-friendly name of the asset.
func (t *IronicVirtualMediaTLS) Name() string {
	return "IronicVirtualMediaTLS"
}

// Generate generates the actual files by this asset.
func (t *IronicVirtualMediaTLS) Generate(_ context.Context, parents asset.Parents) error {
	logrus.Debugf("Generate() ironic vmedia tls")
	t.FileList = []*asset.File{}

	for _, fileName := range []string{
		ironicVirtualMediaTLSCertTemplate,
		ironicVirtualMediaTLSKeyTemplate,
	} {
		data, err := content.GetOpenshiftTemplate(fileName)
		if err != nil {
			logrus.Debugf("Error in Generate() ironic vmedia tls: %q", err)
			return err
		}
		t.FileList = append(t.FileList, &asset.File{
			Filename: filepath.Join(content.TemplateDir, fileName),
			Data:     data,
		})
	}
	return nil
}

// Files returns the files generated by the asset.
func (t *IronicVirtualMediaTLS) Files() []*asset.File {
	logrus.Debugf("Files() ironic vmedia tls")
	return t.FileList
}

// Load returns the asset from disk.
func (t *IronicVirtualMediaTLS) Load(f asset.FileFetcher) (bool, error) {
	logrus.Debugf("Load() ironic vmedia tls")
	t.FileList = []*asset.File{}

	for _, fileName := range []string{
		ironicVirtualMediaTLSCertTemplate,
		ironicVirtualMediaTLSKeyTemplate,
	} {
		file, err := f.FetchByName(filepath.Join(content.TemplateDir, fileName))
		if err != nil {
			if os.IsNotExist(err) {
				return false, nil
			}
			return false, err
		}
		t.FileList = append(t.FileList, file)
	}

	return true, nil
}
