package openshift

import (
	"os"
	"path/filepath"

	"github.com/openshift/installer/pkg/asset"
	"github.com/openshift/installer/pkg/asset/templates/content"
)

const (
	metal3ConfigMapFileName = "metal3-configmap.yaml.template"
)

var _ asset.WritableAsset = (*Metal3ConfigMap)(nil)

// Metal3ConfigMap file list.
type Metal3ConfigMap struct {
	FileList []*asset.File
}

// Dependencies returns all of the dependencies directly needed by the asset
func (t *Metal3ConfigMap) Dependencies() []asset.Asset {
	return []asset.Asset{}
}

// Name returns the human-friendly name of the asset.
func (t *Metal3ConfigMap) Name() string {
	return "Metal3ConfigMap"
}

// Generate generates the actual files by this asset
func (t *Metal3ConfigMap) Generate(parents asset.Parents) error {
	fileName := metal3ConfigMapFileName
	data, err := content.GetOpenshiftTemplate(fileName)
	if err != nil {
		return err
	}
	t.FileList = []*asset.File{
		{
			Filename: filepath.Join(content.TemplateDir, fileName),
			Data:     []byte(data),
		},
	}
	return nil
}

// Files returns the files generated by the asset.
func (t *Metal3ConfigMap) Files() []*asset.File {
	return t.FileList
}

// Load returns the asset from disk.
func (t *Metal3ConfigMap) Load(f asset.FileFetcher) (bool, error) {
	file, err := f.FetchByName(filepath.Join(content.TemplateDir, metal3ConfigMapFileName))
	if err != nil {
		if os.IsNotExist(err) {
			return false, nil
		}
		return false, err
	}
	t.FileList = []*asset.File{file}
	return true, nil
}
