package openshift

import (
	"os"
	"path/filepath"

	"github.com/openshift/installer/pkg/asset"
	"github.com/openshift/installer/pkg/asset/templates/content"
)

const (
	samplesOperatorFilename = "samples-operator.yaml"
)

var _ asset.WritableAsset = (*SamplesOperator)(nil)

// SamplesOperator is the SampleOperator setting for OKD to use only public imagestreams
type SamplesOperator struct {
	FileList []*asset.File
}

// Dependencies returns all of the dependencies directly needed by the asset
func (t *SamplesOperator) Dependencies() []asset.Asset {
	return []asset.Asset{}
}

// Name returns the human-friendly name of the asset.
func (t *SamplesOperator) Name() string {
	return "Samples Operator setting"
}

// Generate generates the actual files by this asset
func (t *SamplesOperator) Generate(parents asset.Parents) error {
	data, err := content.GetOpenshiftTemplate(samplesOperatorFilename)
	if err != nil {
		return err
	}
	t.FileList = append(t.FileList, &asset.File{
		Filename: filepath.Join(content.TemplateDir, samplesOperatorFilename),
		Data:     []byte(data),
	})
	return nil
}

// Files returns the files generated by the asset.
func (t *SamplesOperator) Files() []*asset.File {
	return t.FileList
}

// Load returns the asset from disk.
func (t *SamplesOperator) Load(f asset.FileFetcher) (bool, error) {
	file, err := f.FetchByName(filepath.Join(content.TemplateDir, samplesOperatorFilename))
	if err != nil {
		if os.IsNotExist(err) {
			return false, nil
		}
		return false, err
	}
	t.FileList = append(t.FileList, file)

	return true, nil
}
