package openshift

import (
	"context"
	"os"
	"path/filepath"

	"github.com/openshift/installer/pkg/asset"
	"github.com/openshift/installer/pkg/asset/templates/content"
)

const (
	vsphereMachineAPICredsSecretFileName = "vsphere-machine-api-creds-secret.yaml.template"
)

var _ asset.WritableAsset = (*VSphereMachineAPICredsSecret)(nil)

// VSphereMachineAPICredsSecret is the constant to represent contents of corresponding yaml file
type VSphereMachineAPICredsSecret struct {
	FileList []*asset.File
}

// Dependencies returns all of the dependencies directly needed by the asset
func (t *VSphereMachineAPICredsSecret) Dependencies() []asset.Asset {
	return []asset.Asset{}
}

// Name returns the human-friendly name of the asset.
func (t *VSphereMachineAPICredsSecret) Name() string {
	return "VSphereMachineAPICredsSecret"
}

// Generate generates the actual files by this asset
func (t *VSphereMachineAPICredsSecret) Generate(_ context.Context, parents asset.Parents) error {
	fileName := vsphereMachineAPICredsSecretFileName
	data, err := content.GetOpenshiftTemplate(fileName)
	if err != nil {
		return err
	}
	t.FileList = []*asset.File{
		{
			Filename: filepath.Join(content.TemplateDir, fileName),
			Data:     []byte(data),
		},
	}
	return nil
}

// Files returns the files generated by the asset.
func (t *VSphereMachineAPICredsSecret) Files() []*asset.File {
	return t.FileList
}

// Load returns the asset from disk.
func (t *VSphereMachineAPICredsSecret) Load(f asset.FileFetcher) (bool, error) {
	file, err := f.FetchByName(filepath.Join(content.TemplateDir, vsphereMachineAPICredsSecretFileName))
	if err != nil {
		if os.IsNotExist(err) {
			return false, nil
		}
		return false, err
	}
	t.FileList = []*asset.File{file}
	return true, nil
}
