apiVersion: v1
baseDomain: shiftstack.example.com
controlPlane:
  hyperthreading: Enabled
  architecture: amd64
  name: master
  platform:
    openstack:
      type: ${COMPUTE_FLAVOR}
      failureDomains:
      - computeAvailabilityZone: computeZone1
        storageAvailabilityZone: storageZone1
      - computeAvailabilityZone: computeZone2
        storageAvailabilityZone: storageZone2
      - computeAvailabilityZone: computeZone3
        storageAvailabilityZone: storageZone3
      - computeAvailabilityZone: computeZone1
        storageAvailabilityZone: storageZone2
      - computeAvailabilityZone: computeZone8
        storageAvailabilityZone: storageZone9
  replicas: 3
compute:
- name: worker
  platform:
    openstack:
      type: ${COMPUTE_FLAVOR}
      failureDomains:
      - computeAvailabilityZone: computeZone1
        storageAvailabilityZone: storageZone1
      - computeAvailabilityZone: computeZone2
        storageAvailabilityZone: storageZone2
      - computeAvailabilityZone: computeZone3
        storageAvailabilityZone: storageZone3
      - computeAvailabilityZone: computeZone4
        storageAvailabilityZone: storageZone4
      - computeAvailabilityZone: computeZone5
        storageAvailabilityZone: storageZone5
  replicas: 3
metadata:
  name: failure-domains-1
networking:
  clusterNetwork:
  - cidr: 10.128.0.0/14
    hostPrefix: 23
  machineNetwork:
  - cidr: 10.0.128.0/17
  networkType: OVNKubernetes
  serviceNetwork:
  - 172.30.0.0/16
platform:
  openstack:
    cloud: ${OS_CLOUD}
    externalNetwork: ${EXTERNAL_NETWORK}
    computeFlavor: ${COMPUTE_FLAVOR}  # deprecated in 4.7
    lbFloatingIP: ${API_FIP}
pullSecret: ${PULL_SECRET}
