package machine

import (
	"encoding/json"
	"github.com/coreos/ignition/config/util"
	"os"

	igntypes "github.com/coreos/ignition/config/v2_2/types"
	"github.com/pkg/errors"
        "github.com/apparentlymart/go-cidr/cidr"
        "github.com/sirupsen/logrus"

	"github.com/openshift/installer/pkg/asset"
        "github.com/openshift/installer/pkg/asset/ignition"
	"github.com/openshift/installer/pkg/asset/installconfig"
	"github.com/openshift/installer/pkg/asset/tls"
        ign "github.com/openshift/installer/pkg/asset/ignition"
)

const (
	workerIgnFilename = "worker.ign"
)

// Worker is an asset that generates the ignition config for worker nodes.
type Worker struct {
	Config *igntypes.Config
	File   *asset.File
}

var _ asset.WritableAsset = (*Worker)(nil)

// Dependencies returns the assets on which the Worker asset depends.
func (a *Worker) Dependencies() []asset.Asset {
	return []asset.Asset{
		&installconfig.InstallConfig{},
		&tls.RootCA{},
	}
}

// Generate generates the ignition config for the Worker asset.
func (a *Worker) Generate(dependencies asset.Parents) error {
	installConfig := &installconfig.InstallConfig{}
	rootCA := &tls.RootCA{}
	dependencies.Get(installConfig, rootCA)

	a.Config = pointerIgnitionConfig(installConfig.Config, rootCA.Cert(), "worker")

        // Create network Script
        machineCIDR := &installConfig.Config.Networking.DeprecatedMachineCIDR.IPNet
        defaultGateway, _ := cidr.Host(machineCIDR, 1)
        kube_api_vlan := installConfig.Config.Platform.OpenStack.AciNetExt.KubeApiVLAN
        mtu_value := installConfig.Config.Platform.OpenStack.AciNetExt.Mtu

        if mtu_value == "" {
                mtu_value = "1500"
        }

        networkScriptString, _ := ign.NetworkScript(kube_api_vlan, defaultGateway.String(), mtu_value)
        logrus.Debug(string(networkScriptString))

        a.Config.Storage.Files = append(a.Config.Storage.Files,ignition.FileFromString("/usr/local/bin/kube-api-interface.sh",
			"root", 0555, string(networkScriptString)),ignition.FileFromString("/etc/sysconfig/network-scripts/ifcfg-ens3.4094", "root", 0420, `DEVICE=ens3.4094
               ONBOOT=yes
               BOOTPROTO=dhcp
               MTU=1500
               TYPE=Vlan
               VLAN=yes
               PHYSDEV=ens3
               VLAN_ID=4094
               REORDER_HDR=yes
               GVRP=no
               MVRP=no
               PROXY_METHOD=none
               BROWSER_ONLY=no
               DEFROUTE=no
               IPV4_FAILURE_FATAL=no
               IPV6INIT=no`),ignition.FileFromString("/etc/sysconfig/network-scripts/ifcfg-opflex-conn", "root", 0420, `VLAN=yes
               TYPE=Vlan
               PHYSDEV=ens3
               VLAN_ID=4093
               REORDER_HDR=yes
               GVRP=no
               MVRP=no
               PROXY_METHOD=none
               BROWSER_ONLY=no
               BOOTPROTO=dhcp
               DEFROUTE=no
               IPV4_FAILURE_FATAL=no
               IPV6INIT=no
               NAME=opflex-conn
               DEVICE=ens3.4093
               ONBOOT=yes
               MTU=1500`),ignition.FileFromString("/etc/sysconfig/network-scripts/ifcfg-uplink-conn", "root", 0420, `TYPE=Ethernet
               PROXY_METHOD=none
               BROWSER_ONLY=no
               DEFROUTE=yes
               IPV4_FAILURE_FATAL=no
               IPV6INIT=no
               NAME=uplink-conn
               DEVICE=ens3
               ONBOOT=yes
               BOOTPROTO=none
               MTU=1500`),ignition.FileFromString("/etc/sysconfig/network-scripts/route-opflex-conn", "root", 0420, `ADDRESS0=224.0.0.0
               NETMASK0=240.0.0.0
               METRIC0=1000`),ignition.FileFromString("/etc/sysconfig/network-scripts/route-ens3.4094", "root", 0420, `ADDRESS0=1.103.2.0
               NETMASK0=255.255.255.0
               METRIC0=1000
               GATEWAY0=192.168.0.1`))

	unit := igntypes.Unit{
		Name:    "node-interface.service",
		Enabled: util.BoolToPtr(true),
		Contents: `[Unit]
		Description=Adding Node Network Interface to MachineSet
		Wants=network-online.target
		After=network-online.target
		[Service]
		Type=simple
		ExecStart=/usr/local/bin/kube-api-interface.sh
		[Install]
		WantedBy=multi-user.target`}

	a.Config.Systemd.Units = append(a.Config.Systemd.Units, unit)

	data, err := json.Marshal(a.Config)
	if err != nil {
		return errors.Wrap(err, "failed to marshal Ignition config")
	}
	a.File = &asset.File{
		Filename: workerIgnFilename,
		Data:     data,
	}

	return nil
}

// Name returns the human-friendly name of the asset.
func (a *Worker) Name() string {
	return "Worker Ignition Config"
}

// Files returns the files generated by the asset.
func (a *Worker) Files() []*asset.File {
	if a.File != nil {
		return []*asset.File{a.File}
	}
	return []*asset.File{}
}

// Load returns the worker ignitions from disk.
func (a *Worker) Load(f asset.FileFetcher) (found bool, err error) {
	file, err := f.FetchByName(workerIgnFilename)
	if err != nil {
		if os.IsNotExist(err) {
			return false, nil
		}
		return false, err
	}

	config := &igntypes.Config{}
	if err := json.Unmarshal(file.Data, config); err != nil {
		return false, errors.Wrapf(err, "failed to unmarshal %s", workerIgnFilename)
	}

	a.File, a.Config = file, config
	return true, nil
}
