package gcp

import (
	"context"
	"fmt"

	"github.com/pkg/errors"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/utils/ptr"
	"sigs.k8s.io/yaml"

	imageregistryv1 "github.com/openshift/api/imageregistry/v1"
	operatorv1 "github.com/openshift/api/operator/v1"
	"github.com/openshift/installer/pkg/asset"
	"github.com/openshift/installer/pkg/asset/installconfig"
	"github.com/openshift/installer/pkg/types"
	gcptypes "github.com/openshift/installer/pkg/types/gcp"
)

const (
	imageRegistryConfigFilename = "openshift/99_openshift-imageregistry_cluster-config.yaml"
)

// ImageRegistryConfig generates the Image Registry configuration manifest for GCP.
type ImageRegistryConfig struct {
	ConfigFile *asset.File
}

var _ asset.WritableAsset = (*ImageRegistryConfig)(nil)

// Name returns a human-friendly name for the asset.
func (*ImageRegistryConfig) Name() string {
	return "Image Registry Config"
}

// Dependencies returns all of the dependencies directly needed to generate
// the asset.
func (*ImageRegistryConfig) Dependencies() []asset.Asset {
	return []asset.Asset{
		&installconfig.ClusterID{},
		&installconfig.InstallConfig{},
	}
}

// Generate generates the Image Registry configuration manifest.
func (i *ImageRegistryConfig) Generate(ctx context.Context, dependencies asset.Parents) error {
	clusterID := &installconfig.ClusterID{}
	installConfig := &installconfig.InstallConfig{}
	dependencies.Get(clusterID, installConfig)

	// Only generate for GCP platform
	if installConfig.Config.Platform.GCP == nil {
		return nil
	}

	// Only generate if KMS encryption is configured
	if gcptypes.GetStorageKMSKey(installConfig.Config.Platform.GCP) == nil {
		return nil
	}

	// Determine topology to set appropriate replica count
	// For Single Node OpenShift (1 control plane replica), use 1 registry replica
	// For all other topologies, use 2 replicas
	replicas := 2
	controlPlaneReplicas := ptr.Deref(installConfig.Config.ControlPlane.Replicas, 3)
	if controlPlaneReplicas == 1 {
		replicas = 1
	}

	// Build the config using typed structs
	config := &imageregistryv1.Config{
		TypeMeta: metav1.TypeMeta{
			APIVersion: imageregistryv1.GroupVersion.String(),
			Kind:       "Config",
		},
		ObjectMeta: metav1.ObjectMeta{
			Name: "cluster",
		},
		Spec: imageregistryv1.ImageRegistrySpec{
			OperatorSpec: operatorv1.OperatorSpec{
				ManagementState: operatorv1.Managed,
			},
			Storage: imageregistryv1.ImageRegistryConfigStorage{
				GCS: buildGCSConfig(clusterID.InfraID, installConfig.Config),
			},
			Replicas: int32(replicas),
		},
	}

	configData, err := yaml.Marshal(config)
	if err != nil {
		return errors.Wrap(err, "failed to marshal image registry config")
	}

	i.ConfigFile = &asset.File{
		Filename: imageRegistryConfigFilename,
		Data:     configData,
	}

	return nil
}

// buildGCSConfig constructs the GCS storage configuration for the ImageRegistry CR.
// It creates the bucket name, region, and project ID, and optionally includes
// a KMS key for customer-managed encryption if configured.
func buildGCSConfig(infraID string, ic *types.InstallConfig) *imageregistryv1.ImageRegistryConfigStorageGCS {
	gcsConfig := &imageregistryv1.ImageRegistryConfigStorageGCS{
		Bucket:    fmt.Sprintf("%s-image-registry", infraID),
		Region:    ic.Platform.GCP.Region,
		ProjectID: ic.Platform.GCP.ProjectID,
	}

	// Add KMS key if configured via defaultMachinePlatform
	if kmsKey := gcptypes.GetStorageKMSKey(ic.Platform.GCP); kmsKey != nil {
		keyID := gcptypes.FormatKMSKeyResourcePath(kmsKey, ic.Platform.GCP.ProjectID)
		gcsConfig.KeyID = keyID
	}

	return gcsConfig
}

// Files returns the files generated by the asset.
func (i *ImageRegistryConfig) Files() []*asset.File {
	if i.ConfigFile != nil {
		return []*asset.File{i.ConfigFile}
	}
	return nil
}

// Load returns false since this asset is not written to disk by the user.
func (i *ImageRegistryConfig) Load(f asset.FileFetcher) (bool, error) {
	return false, nil
}
