//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by deepcopy-gen. DO NOT EDIT.

package types

import (
	v1 "github.com/openshift/api/config/v1"
	ipnet "github.com/openshift/installer/pkg/ipnet"
	aws "github.com/openshift/installer/pkg/types/aws"
	azure "github.com/openshift/installer/pkg/types/azure"
	baremetal "github.com/openshift/installer/pkg/types/baremetal"
	external "github.com/openshift/installer/pkg/types/external"
	gcp "github.com/openshift/installer/pkg/types/gcp"
	ibmcloud "github.com/openshift/installer/pkg/types/ibmcloud"
	none "github.com/openshift/installer/pkg/types/none"
	nutanix "github.com/openshift/installer/pkg/types/nutanix"
	openstack "github.com/openshift/installer/pkg/types/openstack"
	ovirt "github.com/openshift/installer/pkg/types/ovirt"
	powervc "github.com/openshift/installer/pkg/types/powervc"
	powervs "github.com/openshift/installer/pkg/types/powervs"
	vsphere "github.com/openshift/installer/pkg/types/vsphere"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BootstrapInPlace) DeepCopyInto(out *BootstrapInPlace) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BootstrapInPlace.
func (in *BootstrapInPlace) DeepCopy() *BootstrapInPlace {
	if in == nil {
		return nil
	}
	out := new(BootstrapInPlace)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Capabilities) DeepCopyInto(out *Capabilities) {
	*out = *in
	if in.AdditionalEnabledCapabilities != nil {
		in, out := &in.AdditionalEnabledCapabilities, &out.AdditionalEnabledCapabilities
		*out = make([]v1.ClusterVersionCapability, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Capabilities.
func (in *Capabilities) DeepCopy() *Capabilities {
	if in == nil {
		return nil
	}
	out := new(Capabilities)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterMetadata) DeepCopyInto(out *ClusterMetadata) {
	*out = *in
	in.ClusterPlatformMetadata.DeepCopyInto(&out.ClusterPlatformMetadata)
	if in.CustomFeatureSet != nil {
		in, out := &in.CustomFeatureSet, &out.CustomFeatureSet
		*out = new(v1.CustomFeatureGates)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterMetadata.
func (in *ClusterMetadata) DeepCopy() *ClusterMetadata {
	if in == nil {
		return nil
	}
	out := new(ClusterMetadata)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterNetworkEntry) DeepCopyInto(out *ClusterNetworkEntry) {
	*out = *in
	in.CIDR.DeepCopyInto(&out.CIDR)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterNetworkEntry.
func (in *ClusterNetworkEntry) DeepCopy() *ClusterNetworkEntry {
	if in == nil {
		return nil
	}
	out := new(ClusterNetworkEntry)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterPlatformMetadata) DeepCopyInto(out *ClusterPlatformMetadata) {
	*out = *in
	if in.AWS != nil {
		in, out := &in.AWS, &out.AWS
		*out = new(aws.Metadata)
		(*in).DeepCopyInto(*out)
	}
	if in.OpenStack != nil {
		in, out := &in.OpenStack, &out.OpenStack
		*out = new(openstack.Metadata)
		(*in).DeepCopyInto(*out)
	}
	if in.Azure != nil {
		in, out := &in.Azure, &out.Azure
		*out = new(azure.Metadata)
		**out = **in
	}
	if in.GCP != nil {
		in, out := &in.GCP, &out.GCP
		*out = new(gcp.Metadata)
		(*in).DeepCopyInto(*out)
	}
	if in.IBMCloud != nil {
		in, out := &in.IBMCloud, &out.IBMCloud
		*out = new(ibmcloud.Metadata)
		(*in).DeepCopyInto(*out)
	}
	if in.BareMetal != nil {
		in, out := &in.BareMetal, &out.BareMetal
		*out = new(baremetal.Metadata)
		**out = **in
	}
	if in.Ovirt != nil {
		in, out := &in.Ovirt, &out.Ovirt
		*out = new(ovirt.Metadata)
		**out = **in
	}
	if in.PowerVC != nil {
		in, out := &in.PowerVC, &out.PowerVC
		*out = new(powervc.Metadata)
		(*in).DeepCopyInto(*out)
	}
	if in.PowerVS != nil {
		in, out := &in.PowerVS, &out.PowerVS
		*out = new(powervs.Metadata)
		(*in).DeepCopyInto(*out)
	}
	if in.VSphere != nil {
		in, out := &in.VSphere, &out.VSphere
		*out = new(vsphere.Metadata)
		(*in).DeepCopyInto(*out)
	}
	if in.Nutanix != nil {
		in, out := &in.Nutanix, &out.Nutanix
		*out = new(nutanix.Metadata)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterPlatformMetadata.
func (in *ClusterPlatformMetadata) DeepCopy() *ClusterPlatformMetadata {
	if in == nil {
		return nil
	}
	out := new(ClusterPlatformMetadata)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterQuota) DeepCopyInto(out *ClusterQuota) {
	*out = *in
	if in.GCP != nil {
		in, out := &in.GCP, &out.GCP
		*out = new(gcp.Quota)
		if **in != nil {
			in, out := *in, *out
			*out = make([]gcp.QuotaUsage, len(*in))
			for i := range *in {
				(*in)[i].DeepCopyInto(&(*out)[i])
			}
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterQuota.
func (in *ClusterQuota) DeepCopy() *ClusterQuota {
	if in == nil {
		return nil
	}
	out := new(ClusterQuota)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Credential) DeepCopyInto(out *Credential) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Credential.
func (in *Credential) DeepCopy() *Credential {
	if in == nil {
		return nil
	}
	out := new(Credential)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Disk) DeepCopyInto(out *Disk) {
	*out = *in
	if in.UserDefined != nil {
		in, out := &in.UserDefined, &out.UserDefined
		*out = new(DiskUserDefined)
		**out = **in
	}
	if in.Etcd != nil {
		in, out := &in.Etcd, &out.Etcd
		*out = new(DiskEtcd)
		**out = **in
	}
	if in.Swap != nil {
		in, out := &in.Swap, &out.Swap
		*out = new(DiskSwap)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Disk.
func (in *Disk) DeepCopy() *Disk {
	if in == nil {
		return nil
	}
	out := new(Disk)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DiskEtcd) DeepCopyInto(out *DiskEtcd) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DiskEtcd.
func (in *DiskEtcd) DeepCopy() *DiskEtcd {
	if in == nil {
		return nil
	}
	out := new(DiskEtcd)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DiskSwap) DeepCopyInto(out *DiskSwap) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DiskSwap.
func (in *DiskSwap) DeepCopy() *DiskSwap {
	if in == nil {
		return nil
	}
	out := new(DiskSwap)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DiskUserDefined) DeepCopyInto(out *DiskUserDefined) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DiskUserDefined.
func (in *DiskUserDefined) DeepCopy() *DiskUserDefined {
	if in == nil {
		return nil
	}
	out := new(DiskUserDefined)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Fencing) DeepCopyInto(out *Fencing) {
	*out = *in
	if in.Credentials != nil {
		in, out := &in.Credentials, &out.Credentials
		*out = make([]*Credential, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(Credential)
				**out = **in
			}
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Fencing.
func (in *Fencing) DeepCopy() *Fencing {
	if in == nil {
		return nil
	}
	out := new(Fencing)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IPv4OVNKubernetesConfig) DeepCopyInto(out *IPv4OVNKubernetesConfig) {
	*out = *in
	if in.InternalJoinSubnet != nil {
		in, out := &in.InternalJoinSubnet, &out.InternalJoinSubnet
		*out = (*in).DeepCopy()
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IPv4OVNKubernetesConfig.
func (in *IPv4OVNKubernetesConfig) DeepCopy() *IPv4OVNKubernetesConfig {
	if in == nil {
		return nil
	}
	out := new(IPv4OVNKubernetesConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ImageContentSource) DeepCopyInto(out *ImageContentSource) {
	*out = *in
	if in.Mirrors != nil {
		in, out := &in.Mirrors, &out.Mirrors
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ImageContentSource.
func (in *ImageContentSource) DeepCopy() *ImageContentSource {
	if in == nil {
		return nil
	}
	out := new(ImageContentSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ImageDigestSource) DeepCopyInto(out *ImageDigestSource) {
	*out = *in
	if in.Mirrors != nil {
		in, out := &in.Mirrors, &out.Mirrors
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ImageDigestSource.
func (in *ImageDigestSource) DeepCopy() *ImageDigestSource {
	if in == nil {
		return nil
	}
	out := new(ImageDigestSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InstallConfig) DeepCopyInto(out *InstallConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	if in.Networking != nil {
		in, out := &in.Networking, &out.Networking
		*out = new(Networking)
		(*in).DeepCopyInto(*out)
	}
	if in.ControlPlane != nil {
		in, out := &in.ControlPlane, &out.ControlPlane
		*out = new(MachinePool)
		(*in).DeepCopyInto(*out)
	}
	if in.Arbiter != nil {
		in, out := &in.Arbiter, &out.Arbiter
		*out = new(MachinePool)
		(*in).DeepCopyInto(*out)
	}
	if in.Compute != nil {
		in, out := &in.Compute, &out.Compute
		*out = make([]MachinePool, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.Platform.DeepCopyInto(&out.Platform)
	if in.Proxy != nil {
		in, out := &in.Proxy, &out.Proxy
		*out = new(Proxy)
		**out = **in
	}
	if in.DeprecatedImageContentSources != nil {
		in, out := &in.DeprecatedImageContentSources, &out.DeprecatedImageContentSources
		*out = make([]ImageContentSource, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ImageDigestSources != nil {
		in, out := &in.ImageDigestSources, &out.ImageDigestSources
		*out = make([]ImageDigestSource, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.OperatorPublishingStrategy != nil {
		in, out := &in.OperatorPublishingStrategy, &out.OperatorPublishingStrategy
		*out = new(OperatorPublishingStrategy)
		**out = **in
	}
	if in.BootstrapInPlace != nil {
		in, out := &in.BootstrapInPlace, &out.BootstrapInPlace
		*out = new(BootstrapInPlace)
		**out = **in
	}
	if in.Capabilities != nil {
		in, out := &in.Capabilities, &out.Capabilities
		*out = new(Capabilities)
		(*in).DeepCopyInto(*out)
	}
	if in.FeatureGates != nil {
		in, out := &in.FeatureGates, &out.FeatureGates
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InstallConfig.
func (in *InstallConfig) DeepCopy() *InstallConfig {
	if in == nil {
		return nil
	}
	out := new(InstallConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MachineNetworkEntry) DeepCopyInto(out *MachineNetworkEntry) {
	*out = *in
	in.CIDR.DeepCopyInto(&out.CIDR)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MachineNetworkEntry.
func (in *MachineNetworkEntry) DeepCopy() *MachineNetworkEntry {
	if in == nil {
		return nil
	}
	out := new(MachineNetworkEntry)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MachinePool) DeepCopyInto(out *MachinePool) {
	*out = *in
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = new(int64)
		**out = **in
	}
	in.Platform.DeepCopyInto(&out.Platform)
	if in.Fencing != nil {
		in, out := &in.Fencing, &out.Fencing
		*out = new(Fencing)
		(*in).DeepCopyInto(*out)
	}
	if in.DiskSetup != nil {
		in, out := &in.DiskSetup, &out.DiskSetup
		*out = make([]Disk, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MachinePool.
func (in *MachinePool) DeepCopy() *MachinePool {
	if in == nil {
		return nil
	}
	out := new(MachinePool)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MachinePoolPlatform) DeepCopyInto(out *MachinePoolPlatform) {
	*out = *in
	if in.AWS != nil {
		in, out := &in.AWS, &out.AWS
		*out = new(aws.MachinePool)
		(*in).DeepCopyInto(*out)
	}
	if in.Azure != nil {
		in, out := &in.Azure, &out.Azure
		*out = new(azure.MachinePool)
		(*in).DeepCopyInto(*out)
	}
	if in.BareMetal != nil {
		in, out := &in.BareMetal, &out.BareMetal
		*out = new(baremetal.MachinePool)
		**out = **in
	}
	if in.GCP != nil {
		in, out := &in.GCP, &out.GCP
		*out = new(gcp.MachinePool)
		(*in).DeepCopyInto(*out)
	}
	if in.IBMCloud != nil {
		in, out := &in.IBMCloud, &out.IBMCloud
		*out = new(ibmcloud.MachinePool)
		(*in).DeepCopyInto(*out)
	}
	if in.OpenStack != nil {
		in, out := &in.OpenStack, &out.OpenStack
		*out = new(openstack.MachinePool)
		(*in).DeepCopyInto(*out)
	}
	if in.VSphere != nil {
		in, out := &in.VSphere, &out.VSphere
		*out = new(vsphere.MachinePool)
		(*in).DeepCopyInto(*out)
	}
	if in.Ovirt != nil {
		in, out := &in.Ovirt, &out.Ovirt
		*out = new(ovirt.MachinePool)
		(*in).DeepCopyInto(*out)
	}
	if in.PowerVC != nil {
		in, out := &in.PowerVC, &out.PowerVC
		*out = new(powervc.MachinePool)
		(*in).DeepCopyInto(*out)
	}
	if in.PowerVS != nil {
		in, out := &in.PowerVS, &out.PowerVS
		*out = new(powervs.MachinePool)
		(*in).DeepCopyInto(*out)
	}
	if in.Nutanix != nil {
		in, out := &in.Nutanix, &out.Nutanix
		*out = new(nutanix.MachinePool)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MachinePoolPlatform.
func (in *MachinePoolPlatform) DeepCopy() *MachinePoolPlatform {
	if in == nil {
		return nil
	}
	out := new(MachinePoolPlatform)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Networking) DeepCopyInto(out *Networking) {
	*out = *in
	if in.MachineNetwork != nil {
		in, out := &in.MachineNetwork, &out.MachineNetwork
		*out = make([]MachineNetworkEntry, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ClusterNetwork != nil {
		in, out := &in.ClusterNetwork, &out.ClusterNetwork
		*out = make([]ClusterNetworkEntry, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ServiceNetwork != nil {
		in, out := &in.ServiceNetwork, &out.ServiceNetwork
		*out = make([]ipnet.IPNet, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.OVNKubernetesConfig != nil {
		in, out := &in.OVNKubernetesConfig, &out.OVNKubernetesConfig
		*out = new(OVNKubernetesConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.DeprecatedMachineCIDR != nil {
		in, out := &in.DeprecatedMachineCIDR, &out.DeprecatedMachineCIDR
		*out = (*in).DeepCopy()
	}
	if in.DeprecatedServiceCIDR != nil {
		in, out := &in.DeprecatedServiceCIDR, &out.DeprecatedServiceCIDR
		*out = (*in).DeepCopy()
	}
	if in.DeprecatedClusterNetworks != nil {
		in, out := &in.DeprecatedClusterNetworks, &out.DeprecatedClusterNetworks
		*out = make([]ClusterNetworkEntry, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Networking.
func (in *Networking) DeepCopy() *Networking {
	if in == nil {
		return nil
	}
	out := new(Networking)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OVNKubernetesConfig) DeepCopyInto(out *OVNKubernetesConfig) {
	*out = *in
	if in.IPv4 != nil {
		in, out := &in.IPv4, &out.IPv4
		*out = new(IPv4OVNKubernetesConfig)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OVNKubernetesConfig.
func (in *OVNKubernetesConfig) DeepCopy() *OVNKubernetesConfig {
	if in == nil {
		return nil
	}
	out := new(OVNKubernetesConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OperatorPublishingStrategy) DeepCopyInto(out *OperatorPublishingStrategy) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OperatorPublishingStrategy.
func (in *OperatorPublishingStrategy) DeepCopy() *OperatorPublishingStrategy {
	if in == nil {
		return nil
	}
	out := new(OperatorPublishingStrategy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Platform) DeepCopyInto(out *Platform) {
	*out = *in
	if in.AWS != nil {
		in, out := &in.AWS, &out.AWS
		*out = new(aws.Platform)
		(*in).DeepCopyInto(*out)
	}
	if in.Azure != nil {
		in, out := &in.Azure, &out.Azure
		*out = new(azure.Platform)
		(*in).DeepCopyInto(*out)
	}
	if in.BareMetal != nil {
		in, out := &in.BareMetal, &out.BareMetal
		*out = new(baremetal.Platform)
		(*in).DeepCopyInto(*out)
	}
	if in.GCP != nil {
		in, out := &in.GCP, &out.GCP
		*out = new(gcp.Platform)
		(*in).DeepCopyInto(*out)
	}
	if in.IBMCloud != nil {
		in, out := &in.IBMCloud, &out.IBMCloud
		*out = new(ibmcloud.Platform)
		(*in).DeepCopyInto(*out)
	}
	if in.None != nil {
		in, out := &in.None, &out.None
		*out = new(none.Platform)
		**out = **in
	}
	if in.External != nil {
		in, out := &in.External, &out.External
		*out = new(external.Platform)
		**out = **in
	}
	if in.OpenStack != nil {
		in, out := &in.OpenStack, &out.OpenStack
		*out = new(openstack.Platform)
		(*in).DeepCopyInto(*out)
	}
	if in.PowerVC != nil {
		in, out := &in.PowerVC, &out.PowerVC
		*out = new(powervc.Platform)
		(*in).DeepCopyInto(*out)
	}
	if in.PowerVS != nil {
		in, out := &in.PowerVS, &out.PowerVS
		*out = new(powervs.Platform)
		(*in).DeepCopyInto(*out)
	}
	if in.VSphere != nil {
		in, out := &in.VSphere, &out.VSphere
		*out = new(vsphere.Platform)
		(*in).DeepCopyInto(*out)
	}
	if in.Ovirt != nil {
		in, out := &in.Ovirt, &out.Ovirt
		*out = new(ovirt.Platform)
		(*in).DeepCopyInto(*out)
	}
	if in.Nutanix != nil {
		in, out := &in.Nutanix, &out.Nutanix
		*out = new(nutanix.Platform)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Platform.
func (in *Platform) DeepCopy() *Platform {
	if in == nil {
		return nil
	}
	out := new(Platform)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Proxy) DeepCopyInto(out *Proxy) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Proxy.
func (in *Proxy) DeepCopy() *Proxy {
	if in == nil {
		return nil
	}
	out := new(Proxy)
	in.DeepCopyInto(out)
	return out
}
