# This Dockerfile is used as a CI job to build smoke tests for OpenShift installer
# FIXME: Move this image to an openshift repo?

FROM  quay.io/coreos/origin-release-oc:bazel
WORKDIR /go/src/github.com/openshift/installer
COPY . .

ENV USER="bazel"
ENV HOME="/tmp"

RUN bazel --output_base=/tmp build smoke_tests && \
    cp bazel-bin/tests/smoke/linux_amd64_stripped/go_default_test /usr/bin/smoke && \
    bazel clean
