package image

import (
	"context"
	"fmt"
	"os"

	"github.com/coreos/stream-metadata-go/arch"
	"github.com/sirupsen/logrus"

	"github.com/openshift/installer/pkg/asset"
	assetrhcos "github.com/openshift/installer/pkg/asset/rhcos"
	"github.com/openshift/installer/pkg/rhcos"
	"github.com/openshift/installer/pkg/rhcos/cache"
	"github.com/openshift/installer/pkg/types"
)

// BaseIso generates the base ISO file for the image.
type BaseIso struct {
	File *asset.File
}

var _ asset.WritableAsset = (*BaseIso)(nil)

// Name returns the human-friendly name of the asset.
func (i *BaseIso) Name() string {
	return "BaseIso Image"
}

// Dependencies returns dependencies used by the asset.
func (i *BaseIso) Dependencies() []asset.Asset {
	return []asset.Asset{
		&ImageBasedInstallationConfig{},
	}
}

// Generate generates the base ISO.
func (i *BaseIso) Generate(ctx context.Context, dependencies asset.Parents) error {
	ibiConfig := &ImageBasedInstallationConfig{}
	dependencies.Get(ibiConfig)

	var err error
	var baseIsoFileName string

	if urlOverride, ok := os.LookupEnv("OPENSHIFT_INSTALL_OS_IMAGE_OVERRIDE"); ok && urlOverride != "" {
		logrus.Warn("Found override for OS Image. Please be warned, this is not advised.")
		baseIsoFileName, err = cache.DownloadImageFile(urlOverride, cache.ImageBasedApplicationName)
	} else {
		architecture := types.ArchitectureAMD64
		if ibiConfig.Config.Architecture != "" {
			architecture = ibiConfig.Config.Architecture
		}
		logrus.Debugf("Using %s as the architecture for the iso", architecture)
		baseIsoFileName, err = i.downloadBaseIso(ctx, arch.RpmArch(architecture))
	}

	if err == nil {
		logrus.Debugf("Using base ISO image %s", baseIsoFileName)
		i.File = &asset.File{Filename: baseIsoFileName}
		return nil
	}
	logrus.Debugf("Failed to download base ISO: %s", err)

	return fmt.Errorf("failed to get base ISO image: %w", err)
}

// Files returns the files generated by the asset.
func (i *BaseIso) Files() []*asset.File {
	if i.File != nil {
		return []*asset.File{i.File}
	}
	return []*asset.File{}
}

// Load is not needed, as Generate uses the rhcos/cache to
// either download the base ISO or return the one found in
// the cache directory.
func (i *BaseIso) Load(f asset.FileFetcher) (bool, error) {
	return false, nil
}

// Download the RHCOS base ISO via rhcos.json.
func (i *BaseIso) downloadBaseIso(ctx context.Context, archName string) (string, error) {
	// Use default OS image stream for image-based installer
	metal, err := assetrhcos.GetMetalArtifact(ctx, archName, rhcos.BuildDefaultOSImageStream())
	if err != nil {
		return "", err
	}

	format, ok := metal.Formats["iso"]
	if !ok {
		return "", fmt.Errorf("no ISO found to download for %s", archName)
	}

	url := format.Disk.Location
	sha := format.Disk.Sha256
	cachedImage, err := cache.DownloadImageFileWithSha(url, cache.ImageBasedApplicationName, sha)
	if err != nil {
		return "", fmt.Errorf("failed to download base ISO image %s: %w", url, err)
	}

	return cachedImage, nil
}
