package bootstrap

import (
	"encoding/json"
	"os"

	igntypes "github.com/coreos/ignition/config/v2_2/types"
	"github.com/pkg/errors"

	"github.com/openshift/installer/pkg/asset"
	"github.com/openshift/installer/pkg/asset/ignition"
	"github.com/openshift/installer/pkg/asset/installconfig"
	"github.com/openshift/installer/pkg/asset/tls"
)

const (
	bootstrapShimIgnFilename = "bootstrap_shim.ign"
)

// Shim holds data with the contents and path to a bootstrap ignition shim file
type Shim struct {
	Config *igntypes.Config
	File   *asset.File
}

var _ asset.WritableAsset = (*Shim)(nil)

// Dependencies returns the assets on which the Bootstrap asset depends.
func (a *Shim) Dependencies() []asset.Asset {
	return []asset.Asset{
		&installconfig.InstallConfig{},
		&tls.RootCA{},
	}
}

// Generate generates the ignition config for the Bootstrap asset.
func (a *Shim) Generate(dependencies asset.Parents) error {
	installConfig := &installconfig.InstallConfig{}
	rootCA := &tls.RootCA{}
	dependencies.Get(installConfig, rootCA)

	a.Config = ignition.PointerIgnitionConfig(installConfig.Config, rootCA.Cert(), "bootstrap")
	data, err := json.Marshal(a.Config)
	if err != nil {
		return errors.Wrap(err, "failed to marshal Ignition config")
	}
	a.File = &asset.File{
		Filename: bootstrapShimIgnFilename,
		Data:     data,
	}

	return nil
}

// Name returns the human-friendly name of the asset.
func (a *Shim) Name() string {
	return "Bootstrap Shim Ignition Config"
}

// Files returns the files generated by the asset.
func (a *Shim) Files() []*asset.File {
	if a.File != nil {
		return []*asset.File{a.File}
	}
	return []*asset.File{}
}

// Load returns the master ignitions from disk.
func (a *Shim) Load(f asset.FileFetcher) (found bool, err error) {
	file, err := f.FetchByName(bootstrapShimIgnFilename)
	if err != nil {
		if os.IsNotExist(err) {
			return false, nil
		}
		return false, err
	}

	config := &igntypes.Config{}
	if err := json.Unmarshal(file.Data, config); err != nil {
		return false, errors.Wrapf(err, "failed to unmarshal %s", bootstrapShimIgnFilename)
	}

	a.File, a.Config = file, config
	return true, nil
}
