// Code generated by MockGen. DO NOT EDIT.
// Source: ./elbclient.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	elb "github.com/aws/aws-sdk-go/service/elb"
	elbv2 "github.com/aws/aws-sdk-go/service/elbv2"
	gomock "github.com/golang/mock/gomock"
)

// MockELBAPI is a mock of ELBAPI interface.
type MockELBAPI struct {
	ctrl     *gomock.Controller
	recorder *MockELBAPIMockRecorder
}

// MockELBAPIMockRecorder is the mock recorder for MockELBAPI.
type MockELBAPIMockRecorder struct {
	mock *MockELBAPI
}

// NewMockELBAPI creates a new mock instance.
func NewMockELBAPI(ctrl *gomock.Controller) *MockELBAPI {
	mock := &MockELBAPI{ctrl: ctrl}
	mock.recorder = &MockELBAPIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockELBAPI) EXPECT() *MockELBAPIMockRecorder {
	return m.recorder
}

// DeleteLoadBalancer mocks base method.
func (m *MockELBAPI) DeleteLoadBalancer(ctx context.Context, name string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteLoadBalancer", ctx, name)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteLoadBalancer indicates an expected call of DeleteLoadBalancer.
func (mr *MockELBAPIMockRecorder) DeleteLoadBalancer(ctx, name interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteLoadBalancer", reflect.TypeOf((*MockELBAPI)(nil).DeleteLoadBalancer), ctx, name)
}

// DescribeLoadBalancersPages mocks base method.
func (m *MockELBAPI) DescribeLoadBalancersPages(ctx context.Context, fn func(*elb.DescribeLoadBalancersOutput, bool) bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DescribeLoadBalancersPages", ctx, fn)
	ret0, _ := ret[0].(error)
	return ret0
}

// DescribeLoadBalancersPages indicates an expected call of DescribeLoadBalancersPages.
func (mr *MockELBAPIMockRecorder) DescribeLoadBalancersPages(ctx, fn interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DescribeLoadBalancersPages", reflect.TypeOf((*MockELBAPI)(nil).DescribeLoadBalancersPages), ctx, fn)
}

// MockELBv2API is a mock of ELBv2API interface.
type MockELBv2API struct {
	ctrl     *gomock.Controller
	recorder *MockELBv2APIMockRecorder
}

// MockELBv2APIMockRecorder is the mock recorder for MockELBv2API.
type MockELBv2APIMockRecorder struct {
	mock *MockELBv2API
}

// NewMockELBv2API creates a new mock instance.
func NewMockELBv2API(ctrl *gomock.Controller) *MockELBv2API {
	mock := &MockELBv2API{ctrl: ctrl}
	mock.recorder = &MockELBv2APIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockELBv2API) EXPECT() *MockELBv2APIMockRecorder {
	return m.recorder
}

// DeleteLoadBalancer mocks base method.
func (m *MockELBv2API) DeleteLoadBalancer(ctx context.Context, name string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteLoadBalancer", ctx, name)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteLoadBalancer indicates an expected call of DeleteLoadBalancer.
func (mr *MockELBv2APIMockRecorder) DeleteLoadBalancer(ctx, name interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteLoadBalancer", reflect.TypeOf((*MockELBv2API)(nil).DeleteLoadBalancer), ctx, name)
}

// DeleteTargetGroup mocks base method.
func (m *MockELBv2API) DeleteTargetGroup(ctx context.Context, arn string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteTargetGroup", ctx, arn)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteTargetGroup indicates an expected call of DeleteTargetGroup.
func (mr *MockELBv2APIMockRecorder) DeleteTargetGroup(ctx, arn interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteTargetGroup", reflect.TypeOf((*MockELBv2API)(nil).DeleteTargetGroup), ctx, arn)
}

// DescribeLoadBalancersPages mocks base method.
func (m *MockELBv2API) DescribeLoadBalancersPages(ctx context.Context, fn func(*elbv2.DescribeLoadBalancersOutput, bool) bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DescribeLoadBalancersPages", ctx, fn)
	ret0, _ := ret[0].(error)
	return ret0
}

// DescribeLoadBalancersPages indicates an expected call of DescribeLoadBalancersPages.
func (mr *MockELBv2APIMockRecorder) DescribeLoadBalancersPages(ctx, fn interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DescribeLoadBalancersPages", reflect.TypeOf((*MockELBv2API)(nil).DescribeLoadBalancersPages), ctx, fn)
}
