#!/usr/bin/env bash
set -e

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
GIT_SHA=$("$DIR/../../git-version")
QUAY_REPO=quay.io/coreos/tectonic-installer

docker build --rm=true -t $QUAY_REPO:$GIT_SHA .
