package manifests

import (
	"context"
	"fmt"
	"path"

	"github.com/sirupsen/logrus"

	"github.com/openshift/installer/pkg/asset"
	"github.com/openshift/installer/pkg/asset/installconfig"
	awsconfig "github.com/openshift/installer/pkg/asset/installconfig/aws"
	awstypes "github.com/openshift/installer/pkg/types/aws"
)

var (
	clusterAuthenticationFilename = path.Join(openshiftManifestDir, "cluster-authentication-02-config.yaml")
)

// Authentication generates the Authentication CR that configures
// the cluster's service account issuer URL.
type Authentication struct {
	FileList []*asset.File
}

var _ asset.WritableAsset = (*Authentication)(nil)

// Name returns a human-friendly name for the asset.
func (*Authentication) Name() string {
	return "Authentication CR"
}

// Dependencies returns all of the dependencies directly needed to generate
// the asset.
func (*Authentication) Dependencies() []asset.Asset {
	return []asset.Asset{
		&installconfig.InstallConfig{},
		&installconfig.ClusterID{},
	}
}

// Generate generates the Authentication CR manifest.
func (a *Authentication) Generate(_ context.Context, dependencies asset.Parents) error {
	installConfig := &installconfig.InstallConfig{}
	clusterID := &installconfig.ClusterID{}
	dependencies.Get(installConfig, clusterID)

	platform := installConfig.Config.Platform
	switch platform.Name() {
	case awstypes.Name:
		if !installConfig.Config.Platform.AWS.IsSTSManaged() {
			return nil
		}

		issuerURL, err := awsconfig.OIDCIssuerURL(clusterID.InfraID, platform.AWS.Region)
		if err != nil {
			return fmt.Errorf("failed to construct OIDC issuer URL: %w", err)
		}
		manifest := fmt.Sprintf(`apiVersion: config.openshift.io/v1
kind: Authentication
metadata:
  name: cluster
spec:
  serviceAccountIssuer: %s
`, issuerURL)

		a.FileList = []*asset.File{
			{
				Filename: clusterAuthenticationFilename,
				Data:     []byte(manifest),
			},
		}
	default:
		logrus.Debugf("Skipped generating Authentication CR for unsupported platform %s", installConfig.Config.Platform.Name())
	}

	return nil
}

// Files returns the files generated by the asset.
func (a *Authentication) Files() []*asset.File {
	return a.FileList
}

// Load loads the already-rendered files back from disk.
func (a *Authentication) Load(asset.FileFetcher) (bool, error) {
	return false, nil
}
