package manifests

import (
	"context"
	"encoding/json"
	"path"

	"github.com/pkg/errors"
	corev1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"sigs.k8s.io/yaml"

	"github.com/openshift/installer/pkg/asset"
	"github.com/openshift/installer/pkg/asset/installconfig"
	"github.com/openshift/installer/pkg/types/baremetal"
)

var (
	bgpVIPConfigMapFileName = path.Join(manifestDir, "bgp-vip-config.yaml")
)

const (
	bgpVIPConfigMapName      = "bgp-vip-config"
	bgpVIPConfigMapNamespace = "openshift-network-operator"
	bgpVIPConfigMapDataKey   = "config.json"
)

// bgpVIPConfigJSON is the JSON structure stored in the ConfigMap.
type bgpVIPConfigJSON struct {
	LocalASN      int64                       `json:"localASN"`
	Peers         []baremetal.BGPPeerConfig    `json:"peers"`
	Communities   []string                    `json:"communities,omitempty"`
	APIVIPs       []string                    `json:"apiVIPs"`
	IngressVIPs   []string                    `json:"ingressVIPs"`
	HostOverrides map[string]bgpHostOverride  `json:"hostOverrides,omitempty"`
}

// bgpHostOverride stores per-host BGP peer overrides.
type bgpHostOverride struct {
	Peers []baremetal.BGPPeerConfig `json:"peers"`
}

// BGPVIPConfigMap generates the bgp-vip-config ConfigMap for CNO.
type BGPVIPConfigMap struct {
	ConfigMap *corev1.ConfigMap
	File      *asset.File
}

var _ asset.WritableAsset = (*BGPVIPConfigMap)(nil)

// Name returns a human friendly name for the asset.
func (*BGPVIPConfigMap) Name() string {
	return "BGP VIP Config ConfigMap"
}

// Dependencies returns all of the dependencies directly needed to generate
// the asset.
func (*BGPVIPConfigMap) Dependencies() []asset.Asset {
	return []asset.Asset{
		&installconfig.InstallConfig{},
	}
}

// Generate generates the BGP VIP Config ConfigMap.
func (b *BGPVIPConfigMap) Generate(_ context.Context, dependencies asset.Parents) error {
	installConfig := &installconfig.InstallConfig{}
	dependencies.Get(installConfig)

	// Only generate for baremetal platform with BGPVIPConfig set.
	if installConfig.Config.Platform.Name() != baremetal.Name ||
		installConfig.Config.Platform.BareMetal == nil ||
		installConfig.Config.Platform.BareMetal.BGPVIPConfig == nil {
		return nil
	}

	bm := installConfig.Config.Platform.BareMetal
	bgpConfig := bm.BGPVIPConfig

	configData := bgpVIPConfigJSON{
		LocalASN:    bgpConfig.LocalASN,
		Peers:       bgpConfig.Peers,
		Communities: bgpConfig.Communities,
		APIVIPs:     bm.APIVIPs,
		IngressVIPs: bm.IngressVIPs,
	}

	// Collect per-host BGP peer overrides.
	hostOverrides := make(map[string]bgpHostOverride)
	for _, host := range bm.Hosts {
		if host != nil && len(host.BGPPeers) > 0 {
			hostOverrides[host.Name] = bgpHostOverride{
				Peers: host.BGPPeers,
			}
		}
	}
	if len(hostOverrides) > 0 {
		configData.HostOverrides = hostOverrides
	}

	jsonBytes, err := json.Marshal(configData)
	if err != nil {
		return errors.Wrap(err, "failed to marshal BGP VIP config JSON")
	}

	cm := &corev1.ConfigMap{
		TypeMeta: metav1.TypeMeta{
			APIVersion: corev1.SchemeGroupVersion.String(),
			Kind:       "ConfigMap",
		},
		ObjectMeta: metav1.ObjectMeta{
			Namespace: bgpVIPConfigMapNamespace,
			Name:      bgpVIPConfigMapName,
		},
		Data: map[string]string{
			bgpVIPConfigMapDataKey: string(jsonBytes),
		},
	}

	cmData, err := yaml.Marshal(cm)
	if err != nil {
		return errors.Wrapf(err, "failed to create %s manifest", b.Name())
	}
	b.ConfigMap = cm
	b.File = &asset.File{
		Filename: bgpVIPConfigMapFileName,
		Data:     cmData,
	}
	return nil
}

// Files returns the files generated by the asset.
func (b *BGPVIPConfigMap) Files() []*asset.File {
	if b.File != nil {
		return []*asset.File{b.File}
	}
	return []*asset.File{}
}

// Load loads the already-rendered files back from disk.
func (b *BGPVIPConfigMap) Load(f asset.FileFetcher) (bool, error) {
	return false, nil
}
