package manifests

import (
	"context"
	"path"

	"github.com/pkg/errors"
	corev1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"sigs.k8s.io/yaml"

	"github.com/openshift/installer/pkg/asset"
	"github.com/openshift/installer/pkg/asset/installconfig"
	"github.com/openshift/installer/pkg/types/baremetal"
)

var (
	bmcVerifyCAConfigMapFileName = path.Join("manifests", "bmc-verify-ca-configmap.yaml")
)

const (
	bmcVerifyCAConfigMapName      = "bmc-verify-ca"
	bmcVerifyCAConfigMapNamespace = "openshift-machine-api"
	bmcVerifyCAConfigMapDataKey   = "verify_ca.crt"
)

// BMCVerifyCAConfigMap generates the bmc-verify-ca ConfigMap.
type BMCVerifyCAConfigMap struct {
	ConfigMap *corev1.ConfigMap
	File      *asset.File
}

var _ asset.WritableAsset = (*BMCVerifyCAConfigMap)(nil)

// Name returns a human friendly name for the asset.
func (*BMCVerifyCAConfigMap) Name() string {
	return "BMC Verify CA ConfigMap"
}

// Dependencies returns all of the dependencies directly needed to generate
// the asset.
func (*BMCVerifyCAConfigMap) Dependencies() []asset.Asset {
	return []asset.Asset{
		&installconfig.InstallConfig{},
	}
}

// Generate generates the BMC Verify CA ConfigMap.
func (bvc *BMCVerifyCAConfigMap) Generate(_ context.Context, dependencies asset.Parents) error {
	installConfig := &installconfig.InstallConfig{}
	dependencies.Get(installConfig)

	// Only generate the file for baremetal platform with BMCVerifyCA configured
	if installConfig.Config.Platform.Name() != baremetal.Name || installConfig.Config.Platform.BareMetal == nil || installConfig.Config.Platform.BareMetal.BMCVerifyCA == "" {
		return nil
	}

	cm := &corev1.ConfigMap{
		TypeMeta: metav1.TypeMeta{
			APIVersion: corev1.SchemeGroupVersion.String(),
			Kind:       "ConfigMap",
		},
		ObjectMeta: metav1.ObjectMeta{
			Namespace: bmcVerifyCAConfigMapNamespace,
			Name:      bmcVerifyCAConfigMapName,
		},
		Data: map[string]string{
			bmcVerifyCAConfigMapDataKey: installConfig.Config.Platform.BareMetal.BMCVerifyCA,
		},
	}

	cmData, err := yaml.Marshal(cm)
	if err != nil {
		return errors.Wrapf(err, "failed to create %s manifest", bvc.Name())
	}
	bvc.ConfigMap = cm
	bvc.File = &asset.File{
		Filename: bmcVerifyCAConfigMapFileName,
		Data:     cmData,
	}
	return nil
}

// Files returns the files generated by the asset.
func (bvc *BMCVerifyCAConfigMap) Files() []*asset.File {
	if bvc.File != nil {
		return []*asset.File{bvc.File}
	}
	return []*asset.File{}
}

// Load loads the already-rendered files back from disk.
func (bvc *BMCVerifyCAConfigMap) Load(f asset.FileFetcher) (bool, error) {
	return false, nil
}
