package manifests

import (
	"context"
	"fmt"
	"path"

	"github.com/aws/aws-sdk-go-v2/service/sts"
	"github.com/sirupsen/logrus"

	"github.com/openshift/installer/pkg/asset"
	"github.com/openshift/installer/pkg/asset/credentialsrequest"
	"github.com/openshift/installer/pkg/asset/installconfig"
	installconfigaws "github.com/openshift/installer/pkg/asset/installconfig/aws"
	awstypes "github.com/openshift/installer/pkg/types/aws"
)

const cloudCredsSecretFilenameFmt = "99_cloud-creds-secret-%s-%s.yaml" //nolint:gosec

// CredentialSecrets generates per-component Secret manifests.
type CredentialSecrets struct {
	FileList []*asset.File
}

var _ asset.WritableAsset = (*CredentialSecrets)(nil)

// Name returns a human-friendly name for the asset.
func (*CredentialSecrets) Name() string {
	return "Credential Secrets"
}

// Dependencies returns all of the dependencies directly needed to generate
// the asset.
func (*CredentialSecrets) Dependencies() []asset.Asset {
	return []asset.Asset{
		&installconfig.InstallConfig{},
		&installconfig.ClusterID{},
		&credentialsrequest.CredentialsRequests{},
	}
}

// Generate generates the credential secret manifests.
func (s *CredentialSecrets) Generate(ctx context.Context, dependencies asset.Parents) error {
	installConfig := &installconfig.InstallConfig{}
	clusterID := &installconfig.ClusterID{}
	credReqs := &credentialsrequest.CredentialsRequests{}
	dependencies.Get(installConfig, clusterID, credReqs)

	platform := installConfig.Config.Platform
	switch platform.Name() {
	case awstypes.Name:
		if !installConfig.Config.Platform.AWS.IsSTSManaged() {
			return nil
		}

		region := platform.AWS.Region
		infraID := clusterID.InfraID

		endpointOpts := installconfigaws.EndpointOptions{
			Region:    region,
			Endpoints: platform.AWS.ServiceEndpoints,
		}

		partitionID, err := installconfigaws.GetPartitionIDForRegion(ctx, region)
		if err != nil {
			return fmt.Errorf("failed to get partition for region %s: %w", region, err)
		}

		stsClient, err := installconfigaws.NewSTSClient(ctx, endpointOpts)
		if err != nil {
			return fmt.Errorf("failed to create STS client: %w", err)
		}

		identity, err := stsClient.GetCallerIdentity(ctx, &sts.GetCallerIdentityInput{})
		if err != nil {
			return fmt.Errorf("failed to get AWS account ID: %w", err)
		}
		accountID := *identity.Account

		for _, cr := range credReqs.Requests {
			roleName := awstypes.STSRoleName(infraID, cr.SecretRefNamespace, cr.SecretRefName)
			roleARN := fmt.Sprintf("arn:%s:iam::%s:role/%s", partitionID, accountID, roleName)

			secretManifest := fmt.Sprintf(`apiVersion: v1
kind: Secret
metadata:
  name: %s
  namespace: %s
stringData:
  credentials: |
    [default]
    sts_regional_endpoints = regional
    role_arn = %s
    web_identity_token_file = /var/run/secrets/openshift/serviceaccount/token
`, cr.SecretRefName, cr.SecretRefNamespace, roleARN)

			filename := fmt.Sprintf(cloudCredsSecretFilenameFmt, cr.SecretRefNamespace, cr.SecretRefName)
			s.FileList = append(s.FileList, &asset.File{
				Filename: path.Join(openshiftManifestDir, filename),
				Data:     []byte(secretManifest),
			})
		}
	default:
		logrus.Debugf("Skipped generating credential secrets for unsupported platform %s", platform.Name())
	}

	return nil
}

// Files returns the files generated by the asset.
func (s *CredentialSecrets) Files() []*asset.File {
	return s.FileList
}

// Load loads the already-rendered files back from disk.
func (s *CredentialSecrets) Load(asset.FileFetcher) (bool, error) {
	return false, nil
}
