package manifests

import (
	"path/filepath"

	"github.com/ghodss/yaml"
	"github.com/pkg/errors"

	configv1 "github.com/openshift/api/config/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"

	"github.com/openshift/installer/pkg/asset"
	"github.com/openshift/installer/pkg/asset/installconfig"
)

var (
	featureGateFilename = filepath.Join(manifestDir, "feature-gate.yml")
)

// FeatureGate generates the feature-gate.yml file.
type FeatureGate struct {
	FileList []*asset.File
}

var _ asset.WritableAsset = (*FeatureGate)(nil)

// Name returns a human friendly name for the asset.
func (*FeatureGate) Name() string {
	return "FeatureGate Manifest"
}

// Dependencies returns all of the dependencies directly needed to generate
// the asset.
func (*FeatureGate) Dependencies() []asset.Asset {
	return []asset.Asset{
		&installconfig.InstallConfig{},
	}
}

// Generate generates the FeatureGate manifest.
func (d *FeatureGate) Generate(dependencies asset.Parents) error {
	installConfig := &installconfig.InstallConfig{}
	dependencies.Get(installConfig)

	fgManifest := &configv1.FeatureGate{
		TypeMeta: metav1.TypeMeta{
			APIVersion: configv1.SchemeGroupVersion.String(),
			Kind:       "FeatureGate",
		},
		ObjectMeta: metav1.ObjectMeta{
			Name: "cluster",
			// not namespaced
		},
		Spec: configv1.FeatureGateSpec{
			FeatureGateSelection: installConfig.Config.FeatureGateSelection,
		},
	}

	manifestData, err := yaml.Marshal(fgManifest)
	if err != nil {
		return errors.Wrapf(err, "failed to create %s manifests from InstallConfig", d.Name())
	}

	d.FileList = []*asset.File{
		{
			Filename: featureGateFilename,
			Data:     manifestData,
		},
	}

	return nil
}

// Files returns the files generated by the asset.
func (d *FeatureGate) Files() []*asset.File {
	return d.FileList
}

// Load loads the already-rendered files back from disk.
func (d *FeatureGate) Load(f asset.FileFetcher) (bool, error) {
	return false, nil
}
