package manifests

import (
	"context"
	"fmt"
	"path"

	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/utils/ptr"
	"sigs.k8s.io/yaml"

	imageregistryv1 "github.com/openshift/api/imageregistry/v1"
	operatorv1 "github.com/openshift/api/operator/v1"
	"github.com/openshift/installer/pkg/asset"
	"github.com/openshift/installer/pkg/asset/installconfig"
	gcpmanifests "github.com/openshift/installer/pkg/asset/manifests/gcp"
	gcptypes "github.com/openshift/installer/pkg/types/gcp"
)

var (
	imageRegistryConfigFilename = path.Join("openshift", "99_openshift-imageregistry_cluster-config.yaml")
)

// ImageRegistryConfig generates the image-registry configuration manifest.
type ImageRegistryConfig struct {
	ConfigFile *asset.File
}

var _ asset.WritableAsset = (*ImageRegistryConfig)(nil)

// Name returns a human-friendly name for the asset.
func (*ImageRegistryConfig) Name() string {
	return "Image Registry Config"
}

// Dependencies returns all of the dependencies directly needed to generate
// the asset.
func (*ImageRegistryConfig) Dependencies() []asset.Asset {
	return []asset.Asset{
		&installconfig.InstallConfig{},
	}
}

// Generate generates the Image Registry configuration manifest.
func (i *ImageRegistryConfig) Generate(ctx context.Context, dependencies asset.Parents) error {
	installConfig := &installconfig.InstallConfig{}
	dependencies.Get(installConfig)

	var storage *imageregistryv1.ImageRegistryConfigStorage

	switch {
	case installConfig.Config.Platform.GCP != nil:
		if gcptypes.GetDefaultEncryptionKey(installConfig.Config.Platform.GCP) == nil {
			return nil
		}
		storage = &imageregistryv1.ImageRegistryConfigStorage{
			GCS: gcpmanifests.BuildGCSConfig(installConfig.Config.Platform.GCP),
		}
	default:
		return nil
	}

	replicas := 2
	controlPlaneReplicas := ptr.Deref(installConfig.Config.ControlPlane.Replicas, 3)
	if controlPlaneReplicas == 1 {
		replicas = 1
	}

	config := &imageregistryv1.Config{
		TypeMeta: metav1.TypeMeta{
			APIVersion: imageregistryv1.GroupVersion.String(),
			Kind:       "Config",
		},
		ObjectMeta: metav1.ObjectMeta{
			Name: "cluster",
		},
		Spec: imageregistryv1.ImageRegistrySpec{
			OperatorSpec: operatorv1.OperatorSpec{
				ManagementState: operatorv1.Managed,
			},
			Storage:  *storage,
			Replicas: int32(replicas),
		},
	}

	configData, err := yaml.Marshal(config)
	if err != nil {
		return fmt.Errorf("failed to marshal image registry config: %w", err)
	}

	i.ConfigFile = &asset.File{
		Filename: imageRegistryConfigFilename,
		Data:     configData,
	}

	return nil
}

// Files returns the files generated by the asset.
func (i *ImageRegistryConfig) Files() []*asset.File {
	if i.ConfigFile != nil {
		return []*asset.File{i.ConfigFile}
	}
	return nil
}

// Load returns false since this asset is not written to disk by the user.
func (i *ImageRegistryConfig) Load(f asset.FileFetcher) (bool, error) {
	return false, nil
}
