package manifests

import (
	"context"
	"fmt"
	"path/filepath"

	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"sigs.k8s.io/yaml"

	operatorv1 "github.com/openshift/api/operator/v1"
	"github.com/openshift/installer/pkg/asset"
	"github.com/openshift/installer/pkg/asset/installconfig"
	"github.com/openshift/installer/pkg/types"
	"github.com/openshift/installer/pkg/types/aws"
	"github.com/openshift/installer/pkg/types/gcp"
)

var (
	mcoCfgFilename = filepath.Join(manifestDir, "cluster-mco-02-config.yml")
)

const (
	roleLabel = "machine.openshift.io/cluster-api-machine-role"
)

// MCO generates the cluster-mco-*.yml files.
type MCO struct {
	FileList []*asset.File
}

var _ asset.WritableAsset = (*MCO)(nil)

// Name returns a human friendly name for the asset.
func (*MCO) Name() string {
	return "MCO Config"
}

// Dependencies returns all of the dependencies directly needed to generate
// the asset.
func (*MCO) Dependencies() []asset.Asset {
	return []asset.Asset{
		&installconfig.InstallConfig{},
	}
}

// Generate generates a machineconfiguration cluster config.
//
// A machineconfiguration cluster config is only created when a user configures custom bootimages,
// in which case we generate a config to disable MCO management of those images.
func (mco *MCO) Generate(_ context.Context, dependencies asset.Parents) error {
	installConfig := &installconfig.InstallConfig{}
	dependencies.Get(installConfig)

	mco.FileList = []*asset.File{}
	if cfg := generateMCOCfg(installConfig.Config); cfg != nil {
		cfgData, err := yaml.Marshal(cfg)
		if err != nil {
			return fmt.Errorf("failed to create %s manifests from InstallConfig: %w", mco.Name(), err)
		}

		mco.FileList = []*asset.File{
			{
				Filename: mcoCfgFilename,
				Data:     cfgData,
			},
		}
	}

	return nil
}

// Files returns the files generated by the asset.
func (mco *MCO) Files() []*asset.File {
	return mco.FileList
}

// Load returns false since this asset is not written to disk by the installer.
func (mco *MCO) Load(asset.FileFetcher) (bool, error) {
	return false, nil
}

func generateMCOCfg(installConfig *types.InstallConfig) *operatorv1.MachineConfiguration {
	cfg := &operatorv1.MachineConfiguration{
		TypeMeta: metav1.TypeMeta{
			APIVersion: operatorv1.SchemeGroupVersion.String(),
			Kind:       "MachineConfiguration",
		},
		ObjectMeta: metav1.ObjectMeta{
			Name:      "cluster",
			Namespace: "openshift-machine-config-operator",
		},
	}

	// Currently the only reason to write an install-time config is if machine managers are needed,
	// otherwise don't write one and defer to default behavior.
	if machineMgrs := machineManagers(installConfig); len(machineMgrs) > 0 {
		cfg.Spec.ManagedBootImages = operatorv1.ManagedBootImages{MachineManagers: machineMgrs}
		return cfg
	}
	return nil
}

func machineManagers(ic *types.InstallConfig) []operatorv1.MachineManager {
	var cpImg, wImg bool
	switch ic.Platform.Name() {
	case aws.Name:
		cpImg, wImg = awsBootImages(ic)
	case gcp.Name:
		cpImg, wImg = gcpBootImages(ic)
	default:
		// We do not need to consider other platforms, because default boot image management has not been enabled yet.
		return nil
	}

	return bootImageMgmt(cpImg, wImg)
}

func awsBootImages(ic *types.InstallConfig) (cpImg bool, wImg bool) {
	if dmp := ic.AWS.DefaultMachinePlatform; dmp != nil && dmp.AMIID != "" {
		return true, true
	}

	if cp := ic.ControlPlane; cp != nil && cp.Platform.AWS != nil && cp.Platform.AWS.AMIID != "" {
		cpImg = true
	}

	if w := ic.Compute; len(w) > 0 && w[0].Platform.AWS != nil && w[0].Platform.AWS.AMIID != "" {
		wImg = true
	}
	return
}

func gcpBootImages(ic *types.InstallConfig) (cpImg bool, wImg bool) {
	if dmp := ic.GCP.DefaultMachinePlatform; dmp != nil && dmp.OSImage != nil {
		return true, true
	}

	if cp := ic.ControlPlane; cp != nil && cp.Platform.GCP != nil && cp.Platform.GCP.OSImage != nil {
		cpImg = true
	}

	if w := ic.Compute; len(w) > 0 && w[0].Platform.GCP != nil && w[0].Platform.GCP.OSImage != nil {
		wImg = true
	}
	return
}

func bootImageMgmt(customCPImg, customWImg bool) []operatorv1.MachineManager {
	var machineManagers []operatorv1.MachineManager

	if !(customCPImg || customWImg) {
		// No custom images, so nothing to do here.
		return nil
	}

	if customCPImg {
		// TODO: when CPMS boot image management is implemented in MCO-1007.
	}

	if customWImg {
		machineManagers = append(machineManagers, operatorv1.MachineManager{
			Resource: operatorv1.MachineSets,
			APIGroup: operatorv1.MachineAPI,
			Selection: operatorv1.MachineManagerSelector{
				Mode: operatorv1.None,
			},
		})
	}

	return machineManagers
}
