package manifests

import (
	"path/filepath"

	"github.com/ghodss/yaml"
	"github.com/pkg/errors"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"

	configv1 "github.com/openshift/api/config/v1"
	"github.com/openshift/installer/pkg/asset"
)

var (
	nodeCfgFilename = filepath.Join(manifestDir, "cluster-node-02-config.yml")
)

// Node generates the cluster-node-02-config.yml files.
type Node struct {
	FileList []*asset.File
}

var _ asset.WritableAsset = (*Node)(nil)

// Name returns a human friendly name for the asset.
func (*Node) Name() string {
	return "Node Config"
}

// Dependencies returns all of the dependencies directly needed to generate
// the asset.
func (*Node) Dependencies() []asset.Asset {
	return []asset.Asset{}
}

// Generate generates the Node config and its CRD.
func (n *Node) Generate(dependencies asset.Parents) error {
	config := &configv1.Node{
		TypeMeta: metav1.TypeMeta{
			APIVersion: configv1.SchemeGroupVersion.String(),
			Kind:       "Node",
		},
		ObjectMeta: metav1.ObjectMeta{
			Name: "cluster",
			// not namespaced
		},
		Spec: configv1.NodeSpec{
			CgroupMode:           configv1.CgroupModeDefault,
			WorkerLatencyProfile: configv1.DefaultUpdateDefaultReaction,
		},
		Status: configv1.NodeStatus{
			WorkerLatencyProfileStatus: configv1.WorkerLatencyProfileStatus{},
		},
	}

	configData, err := yaml.Marshal(config)
	if err != nil {
		return errors.Wrapf(err, "failed to marshal config: %#v", config)
	}
	n.FileList = append(n.FileList, &asset.File{
		Filename: nodeCfgFilename,
		Data:     configData,
	})
	return nil
}

// Files returns the files generated by the asset.
func (n *Node) Files() []*asset.File {
	return n.FileList
}

// Load returns false since this asset is not written to disk by the installer.
func (n *Node) Load(f asset.FileFetcher) (bool, error) {
	return false, nil
}
