package manifests

import (
	"context"
	"path"

	"github.com/pkg/errors"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"sigs.k8s.io/yaml"

	configv1alpha1 "github.com/openshift/api/config/v1alpha1"
	features "github.com/openshift/api/features"
	"github.com/openshift/installer/pkg/asset"
	"github.com/openshift/installer/pkg/asset/installconfig"
	"github.com/openshift/installer/pkg/types"
	libpki "github.com/openshift/library-go/pkg/pki"
)

var pkiCfgFilename = path.Join(manifestDir, "cluster-pki-02-config.yaml")

// PKIConfiguration generates the PKI custom resource manifest.
type PKIConfiguration struct {
	FileList []*asset.File
}

var _ asset.WritableAsset = (*PKIConfiguration)(nil)

// Name returns a human friendly name for the asset.
func (*PKIConfiguration) Name() string {
	return "PKI Config"
}

// Dependencies returns all of the dependencies directly needed to generate
// the asset.
func (*PKIConfiguration) Dependencies() []asset.Asset {
	return []asset.Asset{
		&installconfig.InstallConfig{},
	}
}

// Generate generates the PKI custom resource manifest.
// The manifest is only generated when the ConfigurablePKI feature gate is enabled.
func (p *PKIConfiguration) Generate(_ context.Context, dependencies asset.Parents) error {
	installConfig := &installconfig.InstallConfig{}
	dependencies.Get(installConfig)

	if !installConfig.Config.Enabled(features.FeatureGateConfigurablePKI) {
		return nil
	}

	profile := libpki.DefaultPKIProfile()

	// Overlay user's signerCertificates if specified in install-config
	if installConfig.Config.PKI != nil {
		profile.SignerCertificates = toAPICertificateConfig(installConfig.Config.PKI.SignerCertificates)
	}

	config := &configv1alpha1.PKI{
		TypeMeta: metav1.TypeMeta{
			APIVersion: configv1alpha1.SchemeGroupVersion.String(),
			Kind:       "PKI",
		},
		ObjectMeta: metav1.ObjectMeta{
			Name: "cluster",
		},
		Spec: configv1alpha1.PKISpec{
			CertificateManagement: configv1alpha1.PKICertificateManagement{
				// TODO(htariq): Should this be Default if PKI is unset in the install config?
				Mode: configv1alpha1.PKICertificateManagementModeCustom,
				Custom: configv1alpha1.CustomPKIPolicy{
					PKIProfile: profile,
				},
			},
		},
	}

	configData, err := yaml.Marshal(config)
	if err != nil {
		return errors.Wrapf(err, "failed to marshal PKI config")
	}

	p.FileList = []*asset.File{
		{
			Filename: pkiCfgFilename,
			Data:     configData,
		},
	}

	return nil
}

// Files returns the files generated by the asset.
func (p *PKIConfiguration) Files() []*asset.File {
	return p.FileList
}

// Load returns false since this asset is not written to disk by the installer.
func (p *PKIConfiguration) Load(f asset.FileFetcher) (bool, error) {
	return false, nil
}

// toAPICertificateConfig converts installer-local CertificateConfig to the upstream API type.
func toAPICertificateConfig(local types.CertificateConfig) configv1alpha1.CertificateConfig {
	apiKey := configv1alpha1.KeyConfig{
		Algorithm: configv1alpha1.KeyAlgorithm(local.Key.Algorithm),
	}
	if local.Key.RSA != nil {
		apiKey.RSA = configv1alpha1.RSAKeyConfig{KeySize: local.Key.RSA.KeySize}
	}
	if local.Key.ECDSA != nil {
		apiKey.ECDSA = configv1alpha1.ECDSAKeyConfig{Curve: configv1alpha1.ECDSACurve(local.Key.ECDSA.Curve)}
	}
	return configv1alpha1.CertificateConfig{Key: apiKey}
}
