package manifests

import (
	"context"
	"fmt"
	"path"

	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"sigs.k8s.io/yaml"

	configv1alpha1 "github.com/openshift/api/config/v1alpha1"
	"github.com/openshift/installer/pkg/asset"
	"github.com/openshift/installer/pkg/asset/tls"
	libpki "github.com/openshift/library-go/pkg/pki"
)

var pkiCfgFilename = path.Join(manifestDir, "cluster-pki-02-config.yaml")

// PKIConfiguration generates the PKI custom resource manifest.
type PKIConfiguration struct {
	FileList []*asset.File
}

var _ asset.WritableAsset = (*PKIConfiguration)(nil)

// Name returns a human friendly name for the asset.
func (*PKIConfiguration) Name() string {
	return "PKI Config"
}

// Dependencies returns all of the dependencies directly needed to generate
// the asset.
func (*PKIConfiguration) Dependencies() []asset.Asset {
	return []asset.Asset{
		&tls.SignerKeyParams{},
	}
}

// Generate generates the PKI custom resource manifest.
// The manifest is only generated when the ConfigurablePKI feature gate is enabled.
func (p *PKIConfiguration) Generate(_ context.Context, dependencies asset.Parents) error {
	signerKeyParams := &tls.SignerKeyParams{}
	dependencies.Get(signerKeyParams)

	if !signerKeyParams.ConfigurablePKIEnabled {
		return nil
	}

	certMgmt := configv1alpha1.PKICertificateManagement{
		Mode: configv1alpha1.PKICertificateManagementModeDefault,
	}

	// When ConfigurablePKIEnabled is true but the profile equals the default,
	// it means no user customization was provided.
	defaultProfile := libpki.DefaultPKIProfile()
	if signerKeyParams.Profile != defaultProfile {
		certMgmt = configv1alpha1.PKICertificateManagement{
			Mode: configv1alpha1.PKICertificateManagementModeCustom,
			Custom: configv1alpha1.CustomPKIPolicy{
				PKIProfile: signerKeyParams.Profile,
			},
		}
	}

	config := &configv1alpha1.PKI{
		TypeMeta: metav1.TypeMeta{
			APIVersion: configv1alpha1.SchemeGroupVersion.String(),
			Kind:       "PKI",
		},
		ObjectMeta: metav1.ObjectMeta{
			Name: "cluster",
		},
		Spec: configv1alpha1.PKISpec{
			CertificateManagement: certMgmt,
		},
	}

	configData, err := yaml.Marshal(config)
	if err != nil {
		return fmt.Errorf("failed to marshal PKI config: %w", err)
	}

	p.FileList = []*asset.File{
		{
			Filename: pkiCfgFilename,
			Data:     configData,
		},
	}

	return nil
}

// Files returns the files generated by the asset.
func (p *PKIConfiguration) Files() []*asset.File {
	return p.FileList
}

// Load returns false since this asset is not written to disk by the installer.
func (p *PKIConfiguration) Load(f asset.FileFetcher) (bool, error) {
	return false, nil
}
